// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/VCSECv3.10.14.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.teslamotors.protocol;

@kotlin.jvm.JvmName("-initializeauthenticationResponse")
public inline fun authenticationResponse(block: com.teslamotors.protocol.AuthenticationResponseKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.AuthenticationResponse =
  com.teslamotors.protocol.AuthenticationResponseKt.Dsl._create(com.teslamotors.protocol.VCSEC.AuthenticationResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `VCSEC.AuthenticationResponse`
 */
public object AuthenticationResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.teslamotors.protocol.VCSEC.AuthenticationResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.teslamotors.protocol.VCSEC.AuthenticationResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.teslamotors.protocol.VCSEC.AuthenticationResponse = _builder.build()

    /**
     * `.VCSEC.AuthenticationLevel_E authenticationLevel = 1;`
     */
    public var authenticationLevel: com.teslamotors.protocol.VCSEC.AuthenticationLevel_E
      @JvmName("getAuthenticationLevel")
      get() = _builder.getAuthenticationLevel()
      @JvmName("setAuthenticationLevel")
      set(value) {
        _builder.setAuthenticationLevel(value)
      }
    public var authenticationLevelValue: kotlin.Int
      @JvmName("getAuthenticationLevelValue")
      get() = _builder.getAuthenticationLevelValue()
      @JvmName("setAuthenticationLevelValue")
      set(value) {
        _builder.setAuthenticationLevelValue(value)
      }
    /**
     * `.VCSEC.AuthenticationLevel_E authenticationLevel = 1;`
     */
    public fun clearAuthenticationLevel() {
      _builder.clearAuthenticationLevel()
    }

    /**
     * `uint32 estimatedDistance = 2;`
     */
    public var estimatedDistance: kotlin.Int
      @JvmName("getEstimatedDistance")
      get() = _builder.getEstimatedDistance()
      @JvmName("setEstimatedDistance")
      set(value) {
        _builder.setEstimatedDistance(value)
      }
    /**
     * `uint32 estimatedDistance = 2;`
     */
    public fun clearEstimatedDistance() {
      _builder.clearEstimatedDistance()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.teslamotors.protocol.VCSEC.AuthenticationResponse.copy(block: com.teslamotors.protocol.AuthenticationResponseKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.AuthenticationResponse =
  com.teslamotors.protocol.AuthenticationResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

