// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/VCSECv3.10.14.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.teslamotors.protocol;

@kotlin.jvm.JvmName("-initializeclosureStatuses")
public inline fun closureStatuses(block: com.teslamotors.protocol.ClosureStatusesKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.ClosureStatuses =
  com.teslamotors.protocol.ClosureStatusesKt.Dsl._create(com.teslamotors.protocol.VCSEC.ClosureStatuses.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `VCSEC.ClosureStatuses`
 */
public object ClosureStatusesKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.teslamotors.protocol.VCSEC.ClosureStatuses.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.teslamotors.protocol.VCSEC.ClosureStatuses.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.teslamotors.protocol.VCSEC.ClosureStatuses = _builder.build()

    /**
     * `.VCSEC.ClosureState_E frontDriverDoor = 1;`
     */
    public var frontDriverDoor: com.teslamotors.protocol.VCSEC.ClosureState_E
      @JvmName("getFrontDriverDoor")
      get() = _builder.getFrontDriverDoor()
      @JvmName("setFrontDriverDoor")
      set(value) {
        _builder.setFrontDriverDoor(value)
      }
    public var frontDriverDoorValue: kotlin.Int
      @JvmName("getFrontDriverDoorValue")
      get() = _builder.getFrontDriverDoorValue()
      @JvmName("setFrontDriverDoorValue")
      set(value) {
        _builder.setFrontDriverDoorValue(value)
      }
    /**
     * `.VCSEC.ClosureState_E frontDriverDoor = 1;`
     */
    public fun clearFrontDriverDoor() {
      _builder.clearFrontDriverDoor()
    }

    /**
     * `.VCSEC.ClosureState_E frontPassengerDoor = 2;`
     */
    public var frontPassengerDoor: com.teslamotors.protocol.VCSEC.ClosureState_E
      @JvmName("getFrontPassengerDoor")
      get() = _builder.getFrontPassengerDoor()
      @JvmName("setFrontPassengerDoor")
      set(value) {
        _builder.setFrontPassengerDoor(value)
      }
    public var frontPassengerDoorValue: kotlin.Int
      @JvmName("getFrontPassengerDoorValue")
      get() = _builder.getFrontPassengerDoorValue()
      @JvmName("setFrontPassengerDoorValue")
      set(value) {
        _builder.setFrontPassengerDoorValue(value)
      }
    /**
     * `.VCSEC.ClosureState_E frontPassengerDoor = 2;`
     */
    public fun clearFrontPassengerDoor() {
      _builder.clearFrontPassengerDoor()
    }

    /**
     * `.VCSEC.ClosureState_E rearDriverDoor = 3;`
     */
    public var rearDriverDoor: com.teslamotors.protocol.VCSEC.ClosureState_E
      @JvmName("getRearDriverDoor")
      get() = _builder.getRearDriverDoor()
      @JvmName("setRearDriverDoor")
      set(value) {
        _builder.setRearDriverDoor(value)
      }
    public var rearDriverDoorValue: kotlin.Int
      @JvmName("getRearDriverDoorValue")
      get() = _builder.getRearDriverDoorValue()
      @JvmName("setRearDriverDoorValue")
      set(value) {
        _builder.setRearDriverDoorValue(value)
      }
    /**
     * `.VCSEC.ClosureState_E rearDriverDoor = 3;`
     */
    public fun clearRearDriverDoor() {
      _builder.clearRearDriverDoor()
    }

    /**
     * `.VCSEC.ClosureState_E rearPassengerDoor = 4;`
     */
    public var rearPassengerDoor: com.teslamotors.protocol.VCSEC.ClosureState_E
      @JvmName("getRearPassengerDoor")
      get() = _builder.getRearPassengerDoor()
      @JvmName("setRearPassengerDoor")
      set(value) {
        _builder.setRearPassengerDoor(value)
      }
    public var rearPassengerDoorValue: kotlin.Int
      @JvmName("getRearPassengerDoorValue")
      get() = _builder.getRearPassengerDoorValue()
      @JvmName("setRearPassengerDoorValue")
      set(value) {
        _builder.setRearPassengerDoorValue(value)
      }
    /**
     * `.VCSEC.ClosureState_E rearPassengerDoor = 4;`
     */
    public fun clearRearPassengerDoor() {
      _builder.clearRearPassengerDoor()
    }

    /**
     * `.VCSEC.ClosureState_E rearTrunk = 5;`
     */
    public var rearTrunk: com.teslamotors.protocol.VCSEC.ClosureState_E
      @JvmName("getRearTrunk")
      get() = _builder.getRearTrunk()
      @JvmName("setRearTrunk")
      set(value) {
        _builder.setRearTrunk(value)
      }
    public var rearTrunkValue: kotlin.Int
      @JvmName("getRearTrunkValue")
      get() = _builder.getRearTrunkValue()
      @JvmName("setRearTrunkValue")
      set(value) {
        _builder.setRearTrunkValue(value)
      }
    /**
     * `.VCSEC.ClosureState_E rearTrunk = 5;`
     */
    public fun clearRearTrunk() {
      _builder.clearRearTrunk()
    }

    /**
     * `.VCSEC.ClosureState_E frontTrunk = 6;`
     */
    public var frontTrunk: com.teslamotors.protocol.VCSEC.ClosureState_E
      @JvmName("getFrontTrunk")
      get() = _builder.getFrontTrunk()
      @JvmName("setFrontTrunk")
      set(value) {
        _builder.setFrontTrunk(value)
      }
    public var frontTrunkValue: kotlin.Int
      @JvmName("getFrontTrunkValue")
      get() = _builder.getFrontTrunkValue()
      @JvmName("setFrontTrunkValue")
      set(value) {
        _builder.setFrontTrunkValue(value)
      }
    /**
     * `.VCSEC.ClosureState_E frontTrunk = 6;`
     */
    public fun clearFrontTrunk() {
      _builder.clearFrontTrunk()
    }

    /**
     * `.VCSEC.ClosureState_E chargePort = 7;`
     */
    public var chargePort: com.teslamotors.protocol.VCSEC.ClosureState_E
      @JvmName("getChargePort")
      get() = _builder.getChargePort()
      @JvmName("setChargePort")
      set(value) {
        _builder.setChargePort(value)
      }
    public var chargePortValue: kotlin.Int
      @JvmName("getChargePortValue")
      get() = _builder.getChargePortValue()
      @JvmName("setChargePortValue")
      set(value) {
        _builder.setChargePortValue(value)
      }
    /**
     * `.VCSEC.ClosureState_E chargePort = 7;`
     */
    public fun clearChargePort() {
      _builder.clearChargePort()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.teslamotors.protocol.VCSEC.ClosureStatuses.copy(block: com.teslamotors.protocol.ClosureStatusesKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.ClosureStatuses =
  com.teslamotors.protocol.ClosureStatusesKt.Dsl._create(this.toBuilder()).apply { block() }._build()

