// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/VCSECv3.10.14.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.teslamotors.protocol;

@kotlin.jvm.JvmName("-initializedelaySleepRequest")
public inline fun delaySleepRequest(block: com.teslamotors.protocol.DelaySleepRequestKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.DelaySleepRequest =
  com.teslamotors.protocol.DelaySleepRequestKt.Dsl._create(com.teslamotors.protocol.VCSEC.DelaySleepRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `VCSEC.DelaySleepRequest`
 */
public object DelaySleepRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.teslamotors.protocol.VCSEC.DelaySleepRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.teslamotors.protocol.VCSEC.DelaySleepRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.teslamotors.protocol.VCSEC.DelaySleepRequest = _builder.build()

    /**
     * `uint32 delayTime_ms = 1;`
     */
    public var delayTimeMs: kotlin.Int
      @JvmName("getDelayTimeMs")
      get() = _builder.getDelayTimeMs()
      @JvmName("setDelayTimeMs")
      set(value) {
        _builder.setDelayTimeMs(value)
      }
    /**
     * `uint32 delayTime_ms = 1;`
     */
    public fun clearDelayTimeMs() {
      _builder.clearDelayTimeMs()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.teslamotors.protocol.VCSEC.DelaySleepRequest.copy(block: com.teslamotors.protocol.DelaySleepRequestKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.DelaySleepRequest =
  com.teslamotors.protocol.DelaySleepRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

