// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/VCSECv3.10.14.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.teslamotors.protocol;

@kotlin.jvm.JvmName("-initializeexternalAuthStatus")
public inline fun externalAuthStatus(block: com.teslamotors.protocol.ExternalAuthStatusKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.ExternalAuthStatus =
  com.teslamotors.protocol.ExternalAuthStatusKt.Dsl._create(com.teslamotors.protocol.VCSEC.ExternalAuthStatus.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `VCSEC.ExternalAuthStatus`
 */
public object ExternalAuthStatusKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.teslamotors.protocol.VCSEC.ExternalAuthStatus.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.teslamotors.protocol.VCSEC.ExternalAuthStatus.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.teslamotors.protocol.VCSEC.ExternalAuthStatus = _builder.build()

    /**
     * `bool active = 1;`
     */
    public var active: kotlin.Boolean
      @JvmName("getActive")
      get() = _builder.getActive()
      @JvmName("setActive")
      set(value) {
        _builder.setActive(value)
      }
    /**
     * `bool active = 1;`
     */
    public fun clearActive() {
      _builder.clearActive()
    }

    /**
     * `.VCSEC.UnsignedMessage messageToBeSignedAsBytes = 2;`
     */
    public var messageToBeSignedAsBytes: com.teslamotors.protocol.VCSEC.UnsignedMessage
      @JvmName("getMessageToBeSignedAsBytes")
      get() = _builder.getMessageToBeSignedAsBytes()
      @JvmName("setMessageToBeSignedAsBytes")
      set(value) {
        _builder.setMessageToBeSignedAsBytes(value)
      }
    /**
     * `.VCSEC.UnsignedMessage messageToBeSignedAsBytes = 2;`
     */
    public fun clearMessageToBeSignedAsBytes() {
      _builder.clearMessageToBeSignedAsBytes()
    }
    /**
     * `.VCSEC.UnsignedMessage messageToBeSignedAsBytes = 2;`
     * @return Whether the messageToBeSignedAsBytes field is set.
     */
    public fun hasMessageToBeSignedAsBytes(): kotlin.Boolean {
      return _builder.hasMessageToBeSignedAsBytes()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.teslamotors.protocol.VCSEC.ExternalAuthStatus.copy(block: com.teslamotors.protocol.ExternalAuthStatusKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.ExternalAuthStatus =
  com.teslamotors.protocol.ExternalAuthStatusKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.teslamotors.protocol.VCSEC.ExternalAuthStatusOrBuilder.messageToBeSignedAsBytesOrNull: com.teslamotors.protocol.VCSEC.UnsignedMessage?
  get() = if (hasMessageToBeSignedAsBytes()) getMessageToBeSignedAsBytes() else null

