// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/VCSECv3.10.14.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.teslamotors.protocol;

@kotlin.jvm.JvmName("-initializefromVCSECMessage")
public inline fun fromVCSECMessage(block: com.teslamotors.protocol.FromVCSECMessageKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.FromVCSECMessage =
  com.teslamotors.protocol.FromVCSECMessageKt.Dsl._create(com.teslamotors.protocol.VCSEC.FromVCSECMessage.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `VCSEC.FromVCSECMessage`
 */
public object FromVCSECMessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.teslamotors.protocol.VCSEC.FromVCSECMessage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.teslamotors.protocol.VCSEC.FromVCSECMessage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.teslamotors.protocol.VCSEC.FromVCSECMessage = _builder.build()

    /**
     * `.VCSEC.VehicleStatus vehicleStatus = 1;`
     */
    public var vehicleStatus: com.teslamotors.protocol.VCSEC.VehicleStatus
      @JvmName("getVehicleStatus")
      get() = _builder.getVehicleStatus()
      @JvmName("setVehicleStatus")
      set(value) {
        _builder.setVehicleStatus(value)
      }
    /**
     * `.VCSEC.VehicleStatus vehicleStatus = 1;`
     */
    public fun clearVehicleStatus() {
      _builder.clearVehicleStatus()
    }
    /**
     * `.VCSEC.VehicleStatus vehicleStatus = 1;`
     * @return Whether the vehicleStatus field is set.
     */
    public fun hasVehicleStatus(): kotlin.Boolean {
      return _builder.hasVehicleStatus()
    }

    /**
     * `.VCSEC.SessionInfo sessionInfo = 2;`
     */
    public var sessionInfo: com.teslamotors.protocol.VCSEC.SessionInfo
      @JvmName("getSessionInfo")
      get() = _builder.getSessionInfo()
      @JvmName("setSessionInfo")
      set(value) {
        _builder.setSessionInfo(value)
      }
    /**
     * `.VCSEC.SessionInfo sessionInfo = 2;`
     */
    public fun clearSessionInfo() {
      _builder.clearSessionInfo()
    }
    /**
     * `.VCSEC.SessionInfo sessionInfo = 2;`
     * @return Whether the sessionInfo field is set.
     */
    public fun hasSessionInfo(): kotlin.Boolean {
      return _builder.hasSessionInfo()
    }

    /**
     * `.VCSEC.AuthenticationRequest authenticationRequest = 3;`
     */
    public var authenticationRequest: com.teslamotors.protocol.VCSEC.AuthenticationRequest
      @JvmName("getAuthenticationRequest")
      get() = _builder.getAuthenticationRequest()
      @JvmName("setAuthenticationRequest")
      set(value) {
        _builder.setAuthenticationRequest(value)
      }
    /**
     * `.VCSEC.AuthenticationRequest authenticationRequest = 3;`
     */
    public fun clearAuthenticationRequest() {
      _builder.clearAuthenticationRequest()
    }
    /**
     * `.VCSEC.AuthenticationRequest authenticationRequest = 3;`
     * @return Whether the authenticationRequest field is set.
     */
    public fun hasAuthenticationRequest(): kotlin.Boolean {
      return _builder.hasAuthenticationRequest()
    }

    /**
     * `.VCSEC.CommandStatus commandStatus = 4;`
     */
    public var commandStatus: com.teslamotors.protocol.VCSEC.CommandStatus
      @JvmName("getCommandStatus")
      get() = _builder.getCommandStatus()
      @JvmName("setCommandStatus")
      set(value) {
        _builder.setCommandStatus(value)
      }
    /**
     * `.VCSEC.CommandStatus commandStatus = 4;`
     */
    public fun clearCommandStatus() {
      _builder.clearCommandStatus()
    }
    /**
     * `.VCSEC.CommandStatus commandStatus = 4;`
     * @return Whether the commandStatus field is set.
     */
    public fun hasCommandStatus(): kotlin.Boolean {
      return _builder.hasCommandStatus()
    }

    /**
     * `.VCSEC.PersonalizationInformation personalizationInformation = 5;`
     */
    public var personalizationInformation: com.teslamotors.protocol.VCSEC.PersonalizationInformation
      @JvmName("getPersonalizationInformation")
      get() = _builder.getPersonalizationInformation()
      @JvmName("setPersonalizationInformation")
      set(value) {
        _builder.setPersonalizationInformation(value)
      }
    /**
     * `.VCSEC.PersonalizationInformation personalizationInformation = 5;`
     */
    public fun clearPersonalizationInformation() {
      _builder.clearPersonalizationInformation()
    }
    /**
     * `.VCSEC.PersonalizationInformation personalizationInformation = 5;`
     * @return Whether the personalizationInformation field is set.
     */
    public fun hasPersonalizationInformation(): kotlin.Boolean {
      return _builder.hasPersonalizationInformation()
    }

    /**
     * `.VCSEC.WhitelistInfo whitelistInfo = 16;`
     */
    public var whitelistInfo: com.teslamotors.protocol.VCSEC.WhitelistInfo
      @JvmName("getWhitelistInfo")
      get() = _builder.getWhitelistInfo()
      @JvmName("setWhitelistInfo")
      set(value) {
        _builder.setWhitelistInfo(value)
      }
    /**
     * `.VCSEC.WhitelistInfo whitelistInfo = 16;`
     */
    public fun clearWhitelistInfo() {
      _builder.clearWhitelistInfo()
    }
    /**
     * `.VCSEC.WhitelistInfo whitelistInfo = 16;`
     * @return Whether the whitelistInfo field is set.
     */
    public fun hasWhitelistInfo(): kotlin.Boolean {
      return _builder.hasWhitelistInfo()
    }

    /**
     * `.VCSEC.WhitelistEntryInfo whitelistEntryInfo = 17;`
     */
    public var whitelistEntryInfo: com.teslamotors.protocol.VCSEC.WhitelistEntryInfo
      @JvmName("getWhitelistEntryInfo")
      get() = _builder.getWhitelistEntryInfo()
      @JvmName("setWhitelistEntryInfo")
      set(value) {
        _builder.setWhitelistEntryInfo(value)
      }
    /**
     * `.VCSEC.WhitelistEntryInfo whitelistEntryInfo = 17;`
     */
    public fun clearWhitelistEntryInfo() {
      _builder.clearWhitelistEntryInfo()
    }
    /**
     * `.VCSEC.WhitelistEntryInfo whitelistEntryInfo = 17;`
     * @return Whether the whitelistEntryInfo field is set.
     */
    public fun hasWhitelistEntryInfo(): kotlin.Boolean {
      return _builder.hasWhitelistEntryInfo()
    }

    /**
     * `.VCSEC.VehicleInfo vehicleInfo = 18;`
     */
    public var vehicleInfo: com.teslamotors.protocol.VCSEC.VehicleInfo
      @JvmName("getVehicleInfo")
      get() = _builder.getVehicleInfo()
      @JvmName("setVehicleInfo")
      set(value) {
        _builder.setVehicleInfo(value)
      }
    /**
     * `.VCSEC.VehicleInfo vehicleInfo = 18;`
     */
    public fun clearVehicleInfo() {
      _builder.clearVehicleInfo()
    }
    /**
     * `.VCSEC.VehicleInfo vehicleInfo = 18;`
     * @return Whether the vehicleInfo field is set.
     */
    public fun hasVehicleInfo(): kotlin.Boolean {
      return _builder.hasVehicleInfo()
    }

    /**
     * `.VCSEC.Capabilities capabilities = 19;`
     */
    public var capabilities: com.teslamotors.protocol.VCSEC.Capabilities
      @JvmName("getCapabilities")
      get() = _builder.getCapabilities()
      @JvmName("setCapabilities")
      set(value) {
        _builder.setCapabilities(value)
      }
    /**
     * `.VCSEC.Capabilities capabilities = 19;`
     */
    public fun clearCapabilities() {
      _builder.clearCapabilities()
    }
    /**
     * `.VCSEC.Capabilities capabilities = 19;`
     * @return Whether the capabilities field is set.
     */
    public fun hasCapabilities(): kotlin.Boolean {
      return _builder.hasCapabilities()
    }

    /**
     * `.VCSEC.ExternalAuthStatus externalAuthStatus = 20;`
     */
    public var externalAuthStatus: com.teslamotors.protocol.VCSEC.ExternalAuthStatus
      @JvmName("getExternalAuthStatus")
      get() = _builder.getExternalAuthStatus()
      @JvmName("setExternalAuthStatus")
      set(value) {
        _builder.setExternalAuthStatus(value)
      }
    /**
     * `.VCSEC.ExternalAuthStatus externalAuthStatus = 20;`
     */
    public fun clearExternalAuthStatus() {
      _builder.clearExternalAuthStatus()
    }
    /**
     * `.VCSEC.ExternalAuthStatus externalAuthStatus = 20;`
     * @return Whether the externalAuthStatus field is set.
     */
    public fun hasExternalAuthStatus(): kotlin.Boolean {
      return _builder.hasExternalAuthStatus()
    }

    /**
     * `.VCSEC.KeyStatusInfo keyStatusInfo = 21;`
     */
    public var keyStatusInfo: com.teslamotors.protocol.VCSEC.KeyStatusInfo
      @JvmName("getKeyStatusInfo")
      get() = _builder.getKeyStatusInfo()
      @JvmName("setKeyStatusInfo")
      set(value) {
        _builder.setKeyStatusInfo(value)
      }
    /**
     * `.VCSEC.KeyStatusInfo keyStatusInfo = 21;`
     */
    public fun clearKeyStatusInfo() {
      _builder.clearKeyStatusInfo()
    }
    /**
     * `.VCSEC.KeyStatusInfo keyStatusInfo = 21;`
     * @return Whether the keyStatusInfo field is set.
     */
    public fun hasKeyStatusInfo(): kotlin.Boolean {
      return _builder.hasKeyStatusInfo()
    }

    /**
     * `.VCSEC.ActiveKey activeKey = 22;`
     */
    public var activeKey: com.teslamotors.protocol.VCSEC.ActiveKey
      @JvmName("getActiveKey")
      get() = _builder.getActiveKey()
      @JvmName("setActiveKey")
      set(value) {
        _builder.setActiveKey(value)
      }
    /**
     * `.VCSEC.ActiveKey activeKey = 22;`
     */
    public fun clearActiveKey() {
      _builder.clearActiveKey()
    }
    /**
     * `.VCSEC.ActiveKey activeKey = 22;`
     * @return Whether the activeKey field is set.
     */
    public fun hasActiveKey(): kotlin.Boolean {
      return _builder.hasActiveKey()
    }

    /**
     * `.VCSEC.UnknownKeyInfo unknownKeyInfo = 23;`
     */
    public var unknownKeyInfo: com.teslamotors.protocol.VCSEC.UnknownKeyInfo
      @JvmName("getUnknownKeyInfo")
      get() = _builder.getUnknownKeyInfo()
      @JvmName("setUnknownKeyInfo")
      set(value) {
        _builder.setUnknownKeyInfo(value)
      }
    /**
     * `.VCSEC.UnknownKeyInfo unknownKeyInfo = 23;`
     */
    public fun clearUnknownKeyInfo() {
      _builder.clearUnknownKeyInfo()
    }
    /**
     * `.VCSEC.UnknownKeyInfo unknownKeyInfo = 23;`
     * @return Whether the unknownKeyInfo field is set.
     */
    public fun hasUnknownKeyInfo(): kotlin.Boolean {
      return _builder.hasUnknownKeyInfo()
    }

    /**
     * `.VCSEC.UpdaterCommand updaterCommand = 30;`
     */
    public var updaterCommand: com.teslamotors.protocol.VCSEC.UpdaterCommand
      @JvmName("getUpdaterCommand")
      get() = _builder.getUpdaterCommand()
      @JvmName("setUpdaterCommand")
      set(value) {
        _builder.setUpdaterCommand(value)
      }
    /**
     * `.VCSEC.UpdaterCommand updaterCommand = 30;`
     */
    public fun clearUpdaterCommand() {
      _builder.clearUpdaterCommand()
    }
    /**
     * `.VCSEC.UpdaterCommand updaterCommand = 30;`
     * @return Whether the updaterCommand field is set.
     */
    public fun hasUpdaterCommand(): kotlin.Boolean {
      return _builder.hasUpdaterCommand()
    }

    /**
     * `.VCSEC.GenealogyRequest_E genealogyRequest = 31;`
     */
    public var genealogyRequest: com.teslamotors.protocol.VCSEC.GenealogyRequest_E
      @JvmName("getGenealogyRequest")
      get() = _builder.getGenealogyRequest()
      @JvmName("setGenealogyRequest")
      set(value) {
        _builder.setGenealogyRequest(value)
      }
    public var genealogyRequestValue: kotlin.Int
      @JvmName("getGenealogyRequestValue")
      get() = _builder.getGenealogyRequestValue()
      @JvmName("setGenealogyRequestValue")
      set(value) {
        _builder.setGenealogyRequestValue(value)
      }
    /**
     * `.VCSEC.GenealogyRequest_E genealogyRequest = 31;`
     */
    public fun clearGenealogyRequest() {
      _builder.clearGenealogyRequest()
    }
    /**
     * `.VCSEC.GenealogyRequest_E genealogyRequest = 31;`
     * @return Whether the genealogyRequest field is set.
     */
    public fun hasGenealogyRequest(): kotlin.Boolean {
      return _builder.hasGenealogyRequest()
    }

    /**
     * `.VCSEC.SleepManagerRequest sleepManagerRequest = 32;`
     */
    public var sleepManagerRequest: com.teslamotors.protocol.VCSEC.SleepManagerRequest
      @JvmName("getSleepManagerRequest")
      get() = _builder.getSleepManagerRequest()
      @JvmName("setSleepManagerRequest")
      set(value) {
        _builder.setSleepManagerRequest(value)
      }
    /**
     * `.VCSEC.SleepManagerRequest sleepManagerRequest = 32;`
     */
    public fun clearSleepManagerRequest() {
      _builder.clearSleepManagerRequest()
    }
    /**
     * `.VCSEC.SleepManagerRequest sleepManagerRequest = 32;`
     * @return Whether the sleepManagerRequest field is set.
     */
    public fun hasSleepManagerRequest(): kotlin.Boolean {
      return _builder.hasSleepManagerRequest()
    }

    /**
     * `.VCSEC.IMURequest_E imuRequest = 33;`
     */
    public var imuRequest: com.teslamotors.protocol.VCSEC.IMURequest_E
      @JvmName("getImuRequest")
      get() = _builder.getImuRequest()
      @JvmName("setImuRequest")
      set(value) {
        _builder.setImuRequest(value)
      }
    public var imuRequestValue: kotlin.Int
      @JvmName("getImuRequestValue")
      get() = _builder.getImuRequestValue()
      @JvmName("setImuRequestValue")
      set(value) {
        _builder.setImuRequestValue(value)
      }
    /**
     * `.VCSEC.IMURequest_E imuRequest = 33;`
     */
    public fun clearImuRequest() {
      _builder.clearImuRequest()
    }
    /**
     * `.VCSEC.IMURequest_E imuRequest = 33;`
     * @return Whether the imuRequest field is set.
     */
    public fun hasImuRequest(): kotlin.Boolean {
      return _builder.hasImuRequest()
    }

    /**
     * `.VCSEC.NFCSERequest_E nfcseRequest = 34;`
     */
    public var nfcseRequest: com.teslamotors.protocol.VCSEC.NFCSERequest_E
      @JvmName("getNfcseRequest")
      get() = _builder.getNfcseRequest()
      @JvmName("setNfcseRequest")
      set(value) {
        _builder.setNfcseRequest(value)
      }
    public var nfcseRequestValue: kotlin.Int
      @JvmName("getNfcseRequestValue")
      get() = _builder.getNfcseRequestValue()
      @JvmName("setNfcseRequestValue")
      set(value) {
        _builder.setNfcseRequestValue(value)
      }
    /**
     * `.VCSEC.NFCSERequest_E nfcseRequest = 34;`
     */
    public fun clearNfcseRequest() {
      _builder.clearNfcseRequest()
    }
    /**
     * `.VCSEC.NFCSERequest_E nfcseRequest = 34;`
     * @return Whether the nfcseRequest field is set.
     */
    public fun hasNfcseRequest(): kotlin.Boolean {
      return _builder.hasNfcseRequest()
    }

    /**
     * `.VCSEC.TPDataRequest_E TPDataRequest = 35;`
     */
    public var tPDataRequest: com.teslamotors.protocol.VCSEC.TPDataRequest_E
      @JvmName("getTPDataRequest")
      get() = _builder.getTPDataRequest()
      @JvmName("setTPDataRequest")
      set(value) {
        _builder.setTPDataRequest(value)
      }
    public var tPDataRequestValue: kotlin.Int
      @JvmName("getTPDataRequestValue")
      get() = _builder.getTPDataRequestValue()
      @JvmName("setTPDataRequestValue")
      set(value) {
        _builder.setTPDataRequestValue(value)
      }
    /**
     * `.VCSEC.TPDataRequest_E TPDataRequest = 35;`
     */
    public fun clearTPDataRequest() {
      _builder.clearTPDataRequest()
    }
    /**
     * `.VCSEC.TPDataRequest_E TPDataRequest = 35;`
     * @return Whether the tPDataRequest field is set.
     */
    public fun hasTPDataRequest(): kotlin.Boolean {
      return _builder.hasTPDataRequest()
    }

    /**
     * `.VCSEC.ResetTrackerCommand_E resetTrackerCommand = 36;`
     */
    public var resetTrackerCommand: com.teslamotors.protocol.VCSEC.ResetTrackerCommand_E
      @JvmName("getResetTrackerCommand")
      get() = _builder.getResetTrackerCommand()
      @JvmName("setResetTrackerCommand")
      set(value) {
        _builder.setResetTrackerCommand(value)
      }
    public var resetTrackerCommandValue: kotlin.Int
      @JvmName("getResetTrackerCommandValue")
      get() = _builder.getResetTrackerCommandValue()
      @JvmName("setResetTrackerCommandValue")
      set(value) {
        _builder.setResetTrackerCommandValue(value)
      }
    /**
     * `.VCSEC.ResetTrackerCommand_E resetTrackerCommand = 36;`
     */
    public fun clearResetTrackerCommand() {
      _builder.clearResetTrackerCommand()
    }
    /**
     * `.VCSEC.ResetTrackerCommand_E resetTrackerCommand = 36;`
     * @return Whether the resetTrackerCommand field is set.
     */
    public fun hasResetTrackerCommand(): kotlin.Boolean {
      return _builder.hasResetTrackerCommand()
    }

    /**
     * `.VCSEC.TPNotifyTrackerCommand_E TPNotifyTrackerCommand = 37;`
     */
    public var tPNotifyTrackerCommand: com.teslamotors.protocol.VCSEC.TPNotifyTrackerCommand_E
      @JvmName("getTPNotifyTrackerCommand")
      get() = _builder.getTPNotifyTrackerCommand()
      @JvmName("setTPNotifyTrackerCommand")
      set(value) {
        _builder.setTPNotifyTrackerCommand(value)
      }
    public var tPNotifyTrackerCommandValue: kotlin.Int
      @JvmName("getTPNotifyTrackerCommandValue")
      get() = _builder.getTPNotifyTrackerCommandValue()
      @JvmName("setTPNotifyTrackerCommandValue")
      set(value) {
        _builder.setTPNotifyTrackerCommandValue(value)
      }
    /**
     * `.VCSEC.TPNotifyTrackerCommand_E TPNotifyTrackerCommand = 37;`
     */
    public fun clearTPNotifyTrackerCommand() {
      _builder.clearTPNotifyTrackerCommand()
    }
    /**
     * `.VCSEC.TPNotifyTrackerCommand_E TPNotifyTrackerCommand = 37;`
     * @return Whether the tPNotifyTrackerCommand field is set.
     */
    public fun hasTPNotifyTrackerCommand(): kotlin.Boolean {
      return _builder.hasTPNotifyTrackerCommand()
    }

    /**
     * `.VCSEC.SetTPConfigration setTPConfiguration = 38;`
     */
    public var setTPConfiguration: com.teslamotors.protocol.VCSEC.SetTPConfigration
      @JvmName("getSetTPConfiguration")
      get() = _builder.getSetTPConfiguration()
      @JvmName("setSetTPConfiguration")
      set(value) {
        _builder.setSetTPConfiguration(value)
      }
    /**
     * `.VCSEC.SetTPConfigration setTPConfiguration = 38;`
     */
    public fun clearSetTPConfiguration() {
      _builder.clearSetTPConfiguration()
    }
    /**
     * `.VCSEC.SetTPConfigration setTPConfiguration = 38;`
     * @return Whether the setTPConfiguration field is set.
     */
    public fun hasSetTPConfiguration(): kotlin.Boolean {
      return _builder.hasSetTPConfiguration()
    }

    /**
     * `.VCSEC.UnsecureNotification unsecureNotification = 39;`
     */
    public var unsecureNotification: com.teslamotors.protocol.VCSEC.UnsecureNotification
      @JvmName("getUnsecureNotification")
      get() = _builder.getUnsecureNotification()
      @JvmName("setUnsecureNotification")
      set(value) {
        _builder.setUnsecureNotification(value)
      }
    /**
     * `.VCSEC.UnsecureNotification unsecureNotification = 39;`
     */
    public fun clearUnsecureNotification() {
      _builder.clearUnsecureNotification()
    }
    /**
     * `.VCSEC.UnsecureNotification unsecureNotification = 39;`
     * @return Whether the unsecureNotification field is set.
     */
    public fun hasUnsecureNotification(): kotlin.Boolean {
      return _builder.hasUnsecureNotification()
    }
    public val subMessageCase: com.teslamotors.protocol.VCSEC.FromVCSECMessage.SubMessageCase
      @JvmName("getSubMessageCase")
      get() = _builder.getSubMessageCase()

    public fun clearSubMessage() {
      _builder.clearSubMessage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.teslamotors.protocol.VCSEC.FromVCSECMessage.copy(block: com.teslamotors.protocol.FromVCSECMessageKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.FromVCSECMessage =
  com.teslamotors.protocol.FromVCSECMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.teslamotors.protocol.VCSEC.FromVCSECMessageOrBuilder.vehicleStatusOrNull: com.teslamotors.protocol.VCSEC.VehicleStatus?
  get() = if (hasVehicleStatus()) getVehicleStatus() else null

public val com.teslamotors.protocol.VCSEC.FromVCSECMessageOrBuilder.sessionInfoOrNull: com.teslamotors.protocol.VCSEC.SessionInfo?
  get() = if (hasSessionInfo()) getSessionInfo() else null

public val com.teslamotors.protocol.VCSEC.FromVCSECMessageOrBuilder.authenticationRequestOrNull: com.teslamotors.protocol.VCSEC.AuthenticationRequest?
  get() = if (hasAuthenticationRequest()) getAuthenticationRequest() else null

public val com.teslamotors.protocol.VCSEC.FromVCSECMessageOrBuilder.commandStatusOrNull: com.teslamotors.protocol.VCSEC.CommandStatus?
  get() = if (hasCommandStatus()) getCommandStatus() else null

public val com.teslamotors.protocol.VCSEC.FromVCSECMessageOrBuilder.personalizationInformationOrNull: com.teslamotors.protocol.VCSEC.PersonalizationInformation?
  get() = if (hasPersonalizationInformation()) getPersonalizationInformation() else null

public val com.teslamotors.protocol.VCSEC.FromVCSECMessageOrBuilder.whitelistInfoOrNull: com.teslamotors.protocol.VCSEC.WhitelistInfo?
  get() = if (hasWhitelistInfo()) getWhitelistInfo() else null

public val com.teslamotors.protocol.VCSEC.FromVCSECMessageOrBuilder.whitelistEntryInfoOrNull: com.teslamotors.protocol.VCSEC.WhitelistEntryInfo?
  get() = if (hasWhitelistEntryInfo()) getWhitelistEntryInfo() else null

public val com.teslamotors.protocol.VCSEC.FromVCSECMessageOrBuilder.vehicleInfoOrNull: com.teslamotors.protocol.VCSEC.VehicleInfo?
  get() = if (hasVehicleInfo()) getVehicleInfo() else null

public val com.teslamotors.protocol.VCSEC.FromVCSECMessageOrBuilder.capabilitiesOrNull: com.teslamotors.protocol.VCSEC.Capabilities?
  get() = if (hasCapabilities()) getCapabilities() else null

public val com.teslamotors.protocol.VCSEC.FromVCSECMessageOrBuilder.externalAuthStatusOrNull: com.teslamotors.protocol.VCSEC.ExternalAuthStatus?
  get() = if (hasExternalAuthStatus()) getExternalAuthStatus() else null

public val com.teslamotors.protocol.VCSEC.FromVCSECMessageOrBuilder.keyStatusInfoOrNull: com.teslamotors.protocol.VCSEC.KeyStatusInfo?
  get() = if (hasKeyStatusInfo()) getKeyStatusInfo() else null

public val com.teslamotors.protocol.VCSEC.FromVCSECMessageOrBuilder.activeKeyOrNull: com.teslamotors.protocol.VCSEC.ActiveKey?
  get() = if (hasActiveKey()) getActiveKey() else null

public val com.teslamotors.protocol.VCSEC.FromVCSECMessageOrBuilder.unknownKeyInfoOrNull: com.teslamotors.protocol.VCSEC.UnknownKeyInfo?
  get() = if (hasUnknownKeyInfo()) getUnknownKeyInfo() else null

public val com.teslamotors.protocol.VCSEC.FromVCSECMessageOrBuilder.updaterCommandOrNull: com.teslamotors.protocol.VCSEC.UpdaterCommand?
  get() = if (hasUpdaterCommand()) getUpdaterCommand() else null

public val com.teslamotors.protocol.VCSEC.FromVCSECMessageOrBuilder.sleepManagerRequestOrNull: com.teslamotors.protocol.VCSEC.SleepManagerRequest?
  get() = if (hasSleepManagerRequest()) getSleepManagerRequest() else null

public val com.teslamotors.protocol.VCSEC.FromVCSECMessageOrBuilder.setTPConfigurationOrNull: com.teslamotors.protocol.VCSEC.SetTPConfigration?
  get() = if (hasSetTPConfiguration()) getSetTPConfiguration() else null

public val com.teslamotors.protocol.VCSEC.FromVCSECMessageOrBuilder.unsecureNotificationOrNull: com.teslamotors.protocol.VCSEC.UnsecureNotification?
  get() = if (hasUnsecureNotification()) getUnsecureNotification() else null

