// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/VCSECv3.10.14.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.teslamotors.protocol;

@kotlin.jvm.JvmName("-initializefromKeyfobMessage")
public inline fun fromKeyfobMessage(block: com.teslamotors.protocol.FromKeyfobMessageKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.FromKeyfobMessage =
  com.teslamotors.protocol.FromKeyfobMessageKt.Dsl._create(com.teslamotors.protocol.VCSEC.FromKeyfobMessage.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `VCSEC.FromKeyfobMessage`
 */
public object FromKeyfobMessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.teslamotors.protocol.VCSEC.FromKeyfobMessage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.teslamotors.protocol.VCSEC.FromKeyfobMessage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.teslamotors.protocol.VCSEC.FromKeyfobMessage = _builder.build()

    /**
     * `.VCSEC.SignedMessage signedMessage = 1;`
     */
    public var signedMessage: com.teslamotors.protocol.VCSEC.SignedMessage
      @JvmName("getSignedMessage")
      get() = _builder.getSignedMessage()
      @JvmName("setSignedMessage")
      set(value) {
        _builder.setSignedMessage(value)
      }
    /**
     * `.VCSEC.SignedMessage signedMessage = 1;`
     */
    public fun clearSignedMessage() {
      _builder.clearSignedMessage()
    }
    /**
     * `.VCSEC.SignedMessage signedMessage = 1;`
     * @return Whether the signedMessage field is set.
     */
    public fun hasSignedMessage(): kotlin.Boolean {
      return _builder.hasSignedMessage()
    }

    /**
     * `.VCSEC.UnsignedMessageShort unsignedMessage = 2;`
     */
    public var unsignedMessage: com.teslamotors.protocol.VCSEC.UnsignedMessageShort
      @JvmName("getUnsignedMessage")
      get() = _builder.getUnsignedMessage()
      @JvmName("setUnsignedMessage")
      set(value) {
        _builder.setUnsignedMessage(value)
      }
    /**
     * `.VCSEC.UnsignedMessageShort unsignedMessage = 2;`
     */
    public fun clearUnsignedMessage() {
      _builder.clearUnsignedMessage()
    }
    /**
     * `.VCSEC.UnsignedMessageShort unsignedMessage = 2;`
     * @return Whether the unsignedMessage field is set.
     */
    public fun hasUnsignedMessage(): kotlin.Boolean {
      return _builder.hasUnsignedMessage()
    }
    public val subMessageCase: com.teslamotors.protocol.VCSEC.FromKeyfobMessage.SubMessageCase
      @JvmName("getSubMessageCase")
      get() = _builder.getSubMessageCase()

    public fun clearSubMessage() {
      _builder.clearSubMessage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.teslamotors.protocol.VCSEC.FromKeyfobMessage.copy(block: com.teslamotors.protocol.FromKeyfobMessageKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.FromKeyfobMessage =
  com.teslamotors.protocol.FromKeyfobMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.teslamotors.protocol.VCSEC.FromKeyfobMessageOrBuilder.signedMessageOrNull: com.teslamotors.protocol.VCSEC.SignedMessage?
  get() = if (hasSignedMessage()) getSignedMessage() else null

public val com.teslamotors.protocol.VCSEC.FromKeyfobMessageOrBuilder.unsignedMessageOrNull: com.teslamotors.protocol.VCSEC.UnsignedMessageShort?
  get() = if (hasUnsignedMessage()) getUnsignedMessage() else null

