// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/VCSECv3.10.14.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.teslamotors.protocol;

@kotlin.jvm.JvmName("-initializegenealogyResponse")
public inline fun genealogyResponse(block: com.teslamotors.protocol.GenealogyResponseKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.GenealogyResponse =
  com.teslamotors.protocol.GenealogyResponseKt.Dsl._create(com.teslamotors.protocol.VCSEC.GenealogyResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `VCSEC.GenealogyResponse`
 */
public object GenealogyResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.teslamotors.protocol.VCSEC.GenealogyResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.teslamotors.protocol.VCSEC.GenealogyResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.teslamotors.protocol.VCSEC.GenealogyResponse = _builder.build()

    /**
     * `.VCSEC.Genealogy currentGenealogy = 1;`
     */
    public var currentGenealogy: com.teslamotors.protocol.VCSEC.Genealogy
      @JvmName("getCurrentGenealogy")
      get() = _builder.getCurrentGenealogy()
      @JvmName("setCurrentGenealogy")
      set(value) {
        _builder.setCurrentGenealogy(value)
      }
    /**
     * `.VCSEC.Genealogy currentGenealogy = 1;`
     */
    public fun clearCurrentGenealogy() {
      _builder.clearCurrentGenealogy()
    }
    /**
     * `.VCSEC.Genealogy currentGenealogy = 1;`
     * @return Whether the currentGenealogy field is set.
     */
    public fun hasCurrentGenealogy(): kotlin.Boolean {
      return _builder.hasCurrentGenealogy()
    }

    /**
     * `.VCSEC.GenealogyStatus_E status = 2;`
     */
    public var status: com.teslamotors.protocol.VCSEC.GenealogyStatus_E
      @JvmName("getStatus")
      get() = _builder.getStatus()
      @JvmName("setStatus")
      set(value) {
        _builder.setStatus(value)
      }
    public var statusValue: kotlin.Int
      @JvmName("getStatusValue")
      get() = _builder.getStatusValue()
      @JvmName("setStatusValue")
      set(value) {
        _builder.setStatusValue(value)
      }
    /**
     * `.VCSEC.GenealogyStatus_E status = 2;`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.teslamotors.protocol.VCSEC.GenealogyResponse.copy(block: com.teslamotors.protocol.GenealogyResponseKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.GenealogyResponse =
  com.teslamotors.protocol.GenealogyResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.teslamotors.protocol.VCSEC.GenealogyResponseOrBuilder.currentGenealogyOrNull: com.teslamotors.protocol.VCSEC.Genealogy?
  get() = if (hasCurrentGenealogy()) getCurrentGenealogy() else null

