// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/VCSECv3.10.14.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.teslamotors.protocol;

@kotlin.jvm.JvmName("-initializegenealogy")
public inline fun genealogy(block: com.teslamotors.protocol.GenealogyKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.Genealogy =
  com.teslamotors.protocol.GenealogyKt.Dsl._create(com.teslamotors.protocol.VCSEC.Genealogy.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `VCSEC.Genealogy`
 */
public object GenealogyKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.teslamotors.protocol.VCSEC.Genealogy.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.teslamotors.protocol.VCSEC.Genealogy.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.teslamotors.protocol.VCSEC.Genealogy = _builder.build()

    /**
     * `bytes serialNumber = 1;`
     */
    public var serialNumber: com.google.protobuf.ByteString
      @JvmName("getSerialNumber")
      get() = _builder.getSerialNumber()
      @JvmName("setSerialNumber")
      set(value) {
        _builder.setSerialNumber(value)
      }
    /**
     * `bytes serialNumber = 1;`
     */
    public fun clearSerialNumber() {
      _builder.clearSerialNumber()
    }

    /**
     * `bytes partNumber = 2;`
     */
    public var partNumber: com.google.protobuf.ByteString
      @JvmName("getPartNumber")
      get() = _builder.getPartNumber()
      @JvmName("setPartNumber")
      set(value) {
        _builder.setPartNumber(value)
      }
    /**
     * `bytes partNumber = 2;`
     */
    public fun clearPartNumber() {
      _builder.clearPartNumber()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.teslamotors.protocol.VCSEC.Genealogy.copy(block: com.teslamotors.protocol.GenealogyKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.Genealogy =
  com.teslamotors.protocol.GenealogyKt.Dsl._create(this.toBuilder()).apply { block() }._build()

