// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/VCSECv3.10.14.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.teslamotors.protocol;

@kotlin.jvm.JvmName("-initializeinformationRequest")
public inline fun informationRequest(block: com.teslamotors.protocol.InformationRequestKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.InformationRequest =
  com.teslamotors.protocol.InformationRequestKt.Dsl._create(com.teslamotors.protocol.VCSEC.InformationRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `VCSEC.InformationRequest`
 */
public object InformationRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.teslamotors.protocol.VCSEC.InformationRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.teslamotors.protocol.VCSEC.InformationRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.teslamotors.protocol.VCSEC.InformationRequest = _builder.build()

    /**
     * `.VCSEC.InformationRequestType informationRequestType = 1;`
     */
    public var informationRequestType: com.teslamotors.protocol.VCSEC.InformationRequestType
      @JvmName("getInformationRequestType")
      get() = _builder.getInformationRequestType()
      @JvmName("setInformationRequestType")
      set(value) {
        _builder.setInformationRequestType(value)
      }
    public var informationRequestTypeValue: kotlin.Int
      @JvmName("getInformationRequestTypeValue")
      get() = _builder.getInformationRequestTypeValue()
      @JvmName("setInformationRequestTypeValue")
      set(value) {
        _builder.setInformationRequestTypeValue(value)
      }
    /**
     * `.VCSEC.InformationRequestType informationRequestType = 1;`
     */
    public fun clearInformationRequestType() {
      _builder.clearInformationRequestType()
    }

    /**
     * `.VCSEC.KeyIdentifier keyId = 2;`
     */
    public var keyId: com.teslamotors.protocol.VCSEC.KeyIdentifier
      @JvmName("getKeyId")
      get() = _builder.getKeyId()
      @JvmName("setKeyId")
      set(value) {
        _builder.setKeyId(value)
      }
    /**
     * `.VCSEC.KeyIdentifier keyId = 2;`
     */
    public fun clearKeyId() {
      _builder.clearKeyId()
    }
    /**
     * `.VCSEC.KeyIdentifier keyId = 2;`
     * @return Whether the keyId field is set.
     */
    public fun hasKeyId(): kotlin.Boolean {
      return _builder.hasKeyId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.teslamotors.protocol.VCSEC.InformationRequest.copy(block: com.teslamotors.protocol.InformationRequestKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.InformationRequest =
  com.teslamotors.protocol.InformationRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.teslamotors.protocol.VCSEC.InformationRequestOrBuilder.keyIdOrNull: com.teslamotors.protocol.VCSEC.KeyIdentifier?
  get() = if (hasKeyId()) getKeyId() else null

