// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/VCSECv3.10.14.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.teslamotors.protocol;

@kotlin.jvm.JvmName("-initializekeyfobInfo")
public inline fun keyfobInfo(block: com.teslamotors.protocol.KeyfobInfoKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.KeyfobInfo =
  com.teslamotors.protocol.KeyfobInfoKt.Dsl._create(com.teslamotors.protocol.VCSEC.KeyfobInfo.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `VCSEC.KeyfobInfo`
 */
public object KeyfobInfoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.teslamotors.protocol.VCSEC.KeyfobInfo.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.teslamotors.protocol.VCSEC.KeyfobInfo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.teslamotors.protocol.VCSEC.KeyfobInfo = _builder.build()

    /**
     * `bytes appCRC = 1;`
     */
    public var appCRC: com.google.protobuf.ByteString
      @JvmName("getAppCRC")
      get() = _builder.getAppCRC()
      @JvmName("setAppCRC")
      set(value) {
        _builder.setAppCRC(value)
      }
    /**
     * `bytes appCRC = 1;`
     */
    public fun clearAppCRC() {
      _builder.clearAppCRC()
    }

    /**
     * `uint32 batteryVoltage_mV = 2;`
     */
    public var batteryVoltageMV: kotlin.Int
      @JvmName("getBatteryVoltageMV")
      get() = _builder.getBatteryVoltageMV()
      @JvmName("setBatteryVoltageMV")
      set(value) {
        _builder.setBatteryVoltageMV(value)
      }
    /**
     * `uint32 batteryVoltage_mV = 2;`
     */
    public fun clearBatteryVoltageMV() {
      _builder.clearBatteryVoltageMV()
    }

    /**
     * `int32 temperature_degreesC = 3;`
     */
    public var temperatureDegreesC: kotlin.Int
      @JvmName("getTemperatureDegreesC")
      get() = _builder.getTemperatureDegreesC()
      @JvmName("setTemperatureDegreesC")
      set(value) {
        _builder.setTemperatureDegreesC(value)
      }
    /**
     * `int32 temperature_degreesC = 3;`
     */
    public fun clearTemperatureDegreesC() {
      _builder.clearTemperatureDegreesC()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.teslamotors.protocol.VCSEC.KeyfobInfo.copy(block: com.teslamotors.protocol.KeyfobInfoKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.KeyfobInfo =
  com.teslamotors.protocol.KeyfobInfoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

