// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/VCSECv3.10.14.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.teslamotors.protocol;

@kotlin.jvm.JvmName("-initializekeyIdentifier")
public inline fun keyIdentifier(block: com.teslamotors.protocol.KeyIdentifierKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.KeyIdentifier =
  com.teslamotors.protocol.KeyIdentifierKt.Dsl._create(com.teslamotors.protocol.VCSEC.KeyIdentifier.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `VCSEC.KeyIdentifier`
 */
public object KeyIdentifierKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.teslamotors.protocol.VCSEC.KeyIdentifier.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.teslamotors.protocol.VCSEC.KeyIdentifier.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.teslamotors.protocol.VCSEC.KeyIdentifier = _builder.build()

    /**
     * `bytes publicKeySHA1 = 1;`
     */
    public var publicKeySHA1: com.google.protobuf.ByteString
      @JvmName("getPublicKeySHA1")
      get() = _builder.getPublicKeySHA1()
      @JvmName("setPublicKeySHA1")
      set(value) {
        _builder.setPublicKeySHA1(value)
      }
    /**
     * `bytes publicKeySHA1 = 1;`
     */
    public fun clearPublicKeySHA1() {
      _builder.clearPublicKeySHA1()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.teslamotors.protocol.VCSEC.KeyIdentifier.copy(block: com.teslamotors.protocol.KeyIdentifierKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.KeyIdentifier =
  com.teslamotors.protocol.KeyIdentifierKt.Dsl._create(this.toBuilder()).apply { block() }._build()

