// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/VCSECv3.10.14.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.teslamotors.protocol;

@kotlin.jvm.JvmName("-initializekeyMetadata")
public inline fun keyMetadata(block: com.teslamotors.protocol.KeyMetadataKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.KeyMetadata =
  com.teslamotors.protocol.KeyMetadataKt.Dsl._create(com.teslamotors.protocol.VCSEC.KeyMetadata.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `VCSEC.KeyMetadata`
 */
public object KeyMetadataKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.teslamotors.protocol.VCSEC.KeyMetadata.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.teslamotors.protocol.VCSEC.KeyMetadata.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.teslamotors.protocol.VCSEC.KeyMetadata = _builder.build()

    /**
     * `.VCSEC.KeyFormFactor keyFormFactor = 1;`
     */
    public var keyFormFactor: com.teslamotors.protocol.VCSEC.KeyFormFactor
      @JvmName("getKeyFormFactor")
      get() = _builder.getKeyFormFactor()
      @JvmName("setKeyFormFactor")
      set(value) {
        _builder.setKeyFormFactor(value)
      }
    public var keyFormFactorValue: kotlin.Int
      @JvmName("getKeyFormFactorValue")
      get() = _builder.getKeyFormFactorValue()
      @JvmName("setKeyFormFactorValue")
      set(value) {
        _builder.setKeyFormFactorValue(value)
      }
    /**
     * `.VCSEC.KeyFormFactor keyFormFactor = 1;`
     */
    public fun clearKeyFormFactor() {
      _builder.clearKeyFormFactor()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.teslamotors.protocol.VCSEC.KeyMetadata.copy(block: com.teslamotors.protocol.KeyMetadataKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.KeyMetadata =
  com.teslamotors.protocol.KeyMetadataKt.Dsl._create(this.toBuilder()).apply { block() }._build()

