// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/VCSECv3.10.14.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.teslamotors.protocol;

@kotlin.jvm.JvmName("-initializekeyStatusInfo")
public inline fun keyStatusInfo(block: com.teslamotors.protocol.KeyStatusInfoKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.KeyStatusInfo =
  com.teslamotors.protocol.KeyStatusInfoKt.Dsl._create(com.teslamotors.protocol.VCSEC.KeyStatusInfo.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `VCSEC.KeyStatusInfo`
 */
public object KeyStatusInfoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.teslamotors.protocol.VCSEC.KeyStatusInfo.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.teslamotors.protocol.VCSEC.KeyStatusInfo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.teslamotors.protocol.VCSEC.KeyStatusInfo = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class KeyStatusesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .VCSEC.KeyStatus keyStatuses = 1;`
     */
     public val keyStatuses: com.google.protobuf.kotlin.DslList<com.teslamotors.protocol.VCSEC.KeyStatus, KeyStatusesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getKeyStatusesList()
      )
    /**
     * `repeated .VCSEC.KeyStatus keyStatuses = 1;`
     * @param value The keyStatuses to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addKeyStatuses")
    public fun com.google.protobuf.kotlin.DslList<com.teslamotors.protocol.VCSEC.KeyStatus, KeyStatusesProxy>.add(value: com.teslamotors.protocol.VCSEC.KeyStatus) {
      _builder.addKeyStatuses(value)
    }
    /**
     * `repeated .VCSEC.KeyStatus keyStatuses = 1;`
     * @param value The keyStatuses to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignKeyStatuses")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.teslamotors.protocol.VCSEC.KeyStatus, KeyStatusesProxy>.plusAssign(value: com.teslamotors.protocol.VCSEC.KeyStatus) {
      add(value)
    }
    /**
     * `repeated .VCSEC.KeyStatus keyStatuses = 1;`
     * @param values The keyStatuses to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllKeyStatuses")
    public fun com.google.protobuf.kotlin.DslList<com.teslamotors.protocol.VCSEC.KeyStatus, KeyStatusesProxy>.addAll(values: kotlin.collections.Iterable<com.teslamotors.protocol.VCSEC.KeyStatus>) {
      _builder.addAllKeyStatuses(values)
    }
    /**
     * `repeated .VCSEC.KeyStatus keyStatuses = 1;`
     * @param values The keyStatuses to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllKeyStatuses")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.teslamotors.protocol.VCSEC.KeyStatus, KeyStatusesProxy>.plusAssign(values: kotlin.collections.Iterable<com.teslamotors.protocol.VCSEC.KeyStatus>) {
      addAll(values)
    }
    /**
     * `repeated .VCSEC.KeyStatus keyStatuses = 1;`
     * @param index The index to set the value at.
     * @param value The keyStatuses to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setKeyStatuses")
    public operator fun com.google.protobuf.kotlin.DslList<com.teslamotors.protocol.VCSEC.KeyStatus, KeyStatusesProxy>.set(index: kotlin.Int, value: com.teslamotors.protocol.VCSEC.KeyStatus) {
      _builder.setKeyStatuses(index, value)
    }
    /**
     * `repeated .VCSEC.KeyStatus keyStatuses = 1;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearKeyStatuses")
    public fun com.google.protobuf.kotlin.DslList<com.teslamotors.protocol.VCSEC.KeyStatus, KeyStatusesProxy>.clear() {
      _builder.clearKeyStatuses()
    }

  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.teslamotors.protocol.VCSEC.KeyStatusInfo.copy(block: com.teslamotors.protocol.KeyStatusInfoKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.KeyStatusInfo =
  com.teslamotors.protocol.KeyStatusInfoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

