// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/VCSECv3.10.14.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.teslamotors.protocol;

@kotlin.jvm.JvmName("-initializephoneInfo")
public inline fun phoneInfo(block: com.teslamotors.protocol.PhoneInfoKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.PhoneInfo =
  com.teslamotors.protocol.PhoneInfoKt.Dsl._create(com.teslamotors.protocol.VCSEC.PhoneInfo.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `VCSEC.PhoneInfo`
 */
public object PhoneInfoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.teslamotors.protocol.VCSEC.PhoneInfo.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.teslamotors.protocol.VCSEC.PhoneInfo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.teslamotors.protocol.VCSEC.PhoneInfo = _builder.build()

    /**
     * `uint32 car_version = 1;`
     */
    public var carVersion: kotlin.Int
      @JvmName("getCarVersion")
      get() = _builder.getCarVersion()
      @JvmName("setCarVersion")
      set(value) {
        _builder.setCarVersion(value)
      }
    /**
     * `uint32 car_version = 1;`
     */
    public fun clearCarVersion() {
      _builder.clearCarVersion()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.teslamotors.protocol.VCSEC.PhoneInfo.copy(block: com.teslamotors.protocol.PhoneInfoKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.PhoneInfo =
  com.teslamotors.protocol.PhoneInfoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

