// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/VCSECv3.10.14.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.teslamotors.protocol;

@kotlin.jvm.JvmName("-initializepublicKey")
public inline fun publicKey(block: com.teslamotors.protocol.PublicKeyKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.PublicKey =
  com.teslamotors.protocol.PublicKeyKt.Dsl._create(com.teslamotors.protocol.VCSEC.PublicKey.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `VCSEC.PublicKey`
 */
public object PublicKeyKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.teslamotors.protocol.VCSEC.PublicKey.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.teslamotors.protocol.VCSEC.PublicKey.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.teslamotors.protocol.VCSEC.PublicKey = _builder.build()

    /**
     * `bytes PublicKeyRaw = 1;`
     */
    public var publicKeyRaw: com.google.protobuf.ByteString
      @JvmName("getPublicKeyRaw")
      get() = _builder.getPublicKeyRaw()
      @JvmName("setPublicKeyRaw")
      set(value) {
        _builder.setPublicKeyRaw(value)
      }
    /**
     * `bytes PublicKeyRaw = 1;`
     */
    public fun clearPublicKeyRaw() {
      _builder.clearPublicKeyRaw()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.teslamotors.protocol.VCSEC.PublicKey.copy(block: com.teslamotors.protocol.PublicKeyKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.PublicKey =
  com.teslamotors.protocol.PublicKeyKt.Dsl._create(this.toBuilder()).apply { block() }._build()

