// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/VCSECv3.10.14.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.teslamotors.protocol;

@kotlin.jvm.JvmName("-initializeresetTrackerStats")
public inline fun resetTrackerStats(block: com.teslamotors.protocol.ResetTrackerStatsKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.ResetTrackerStats =
  com.teslamotors.protocol.ResetTrackerStatsKt.Dsl._create(com.teslamotors.protocol.VCSEC.ResetTrackerStats.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `VCSEC.ResetTrackerStats`
 */
public object ResetTrackerStatsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.teslamotors.protocol.VCSEC.ResetTrackerStats.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.teslamotors.protocol.VCSEC.ResetTrackerStats.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.teslamotors.protocol.VCSEC.ResetTrackerStats = _builder.build()

    /**
     * `uint32 totalResetsDueToPowerOn = 1;`
     */
    public var totalResetsDueToPowerOn: kotlin.Int
      @JvmName("getTotalResetsDueToPowerOn")
      get() = _builder.getTotalResetsDueToPowerOn()
      @JvmName("setTotalResetsDueToPowerOn")
      set(value) {
        _builder.setTotalResetsDueToPowerOn(value)
      }
    /**
     * `uint32 totalResetsDueToPowerOn = 1;`
     */
    public fun clearTotalResetsDueToPowerOn() {
      _builder.clearTotalResetsDueToPowerOn()
    }

    /**
     * `uint32 totalResetsDueToPinReset = 2;`
     */
    public var totalResetsDueToPinReset: kotlin.Int
      @JvmName("getTotalResetsDueToPinReset")
      get() = _builder.getTotalResetsDueToPinReset()
      @JvmName("setTotalResetsDueToPinReset")
      set(value) {
        _builder.setTotalResetsDueToPinReset(value)
      }
    /**
     * `uint32 totalResetsDueToPinReset = 2;`
     */
    public fun clearTotalResetsDueToPinReset() {
      _builder.clearTotalResetsDueToPinReset()
    }

    /**
     * `uint32 totalResetsDueToVDDSLoss = 3;`
     */
    public var totalResetsDueToVDDSLoss: kotlin.Int
      @JvmName("getTotalResetsDueToVDDSLoss")
      get() = _builder.getTotalResetsDueToVDDSLoss()
      @JvmName("setTotalResetsDueToVDDSLoss")
      set(value) {
        _builder.setTotalResetsDueToVDDSLoss(value)
      }
    /**
     * `uint32 totalResetsDueToVDDSLoss = 3;`
     */
    public fun clearTotalResetsDueToVDDSLoss() {
      _builder.clearTotalResetsDueToVDDSLoss()
    }

    /**
     * `uint32 totalResetsDueToVDDLoss = 4;`
     */
    public var totalResetsDueToVDDLoss: kotlin.Int
      @JvmName("getTotalResetsDueToVDDLoss")
      get() = _builder.getTotalResetsDueToVDDLoss()
      @JvmName("setTotalResetsDueToVDDLoss")
      set(value) {
        _builder.setTotalResetsDueToVDDLoss(value)
      }
    /**
     * `uint32 totalResetsDueToVDDLoss = 4;`
     */
    public fun clearTotalResetsDueToVDDLoss() {
      _builder.clearTotalResetsDueToVDDLoss()
    }

    /**
     * `uint32 totalResetsDueToVDDRLoss = 5;`
     */
    public var totalResetsDueToVDDRLoss: kotlin.Int
      @JvmName("getTotalResetsDueToVDDRLoss")
      get() = _builder.getTotalResetsDueToVDDRLoss()
      @JvmName("setTotalResetsDueToVDDRLoss")
      set(value) {
        _builder.setTotalResetsDueToVDDRLoss(value)
      }
    /**
     * `uint32 totalResetsDueToVDDRLoss = 5;`
     */
    public fun clearTotalResetsDueToVDDRLoss() {
      _builder.clearTotalResetsDueToVDDRLoss()
    }

    /**
     * `uint32 totalResetsDueToClockLoss = 6;`
     */
    public var totalResetsDueToClockLoss: kotlin.Int
      @JvmName("getTotalResetsDueToClockLoss")
      get() = _builder.getTotalResetsDueToClockLoss()
      @JvmName("setTotalResetsDueToClockLoss")
      set(value) {
        _builder.setTotalResetsDueToClockLoss(value)
      }
    /**
     * `uint32 totalResetsDueToClockLoss = 6;`
     */
    public fun clearTotalResetsDueToClockLoss() {
      _builder.clearTotalResetsDueToClockLoss()
    }

    /**
     * `uint32 totalResetsDueToSystemReset = 7;`
     */
    public var totalResetsDueToSystemReset: kotlin.Int
      @JvmName("getTotalResetsDueToSystemReset")
      get() = _builder.getTotalResetsDueToSystemReset()
      @JvmName("setTotalResetsDueToSystemReset")
      set(value) {
        _builder.setTotalResetsDueToSystemReset(value)
      }
    /**
     * `uint32 totalResetsDueToSystemReset = 7;`
     */
    public fun clearTotalResetsDueToSystemReset() {
      _builder.clearTotalResetsDueToSystemReset()
    }

    /**
     * `uint32 totalResetsDueToWarmReset = 8;`
     */
    public var totalResetsDueToWarmReset: kotlin.Int
      @JvmName("getTotalResetsDueToWarmReset")
      get() = _builder.getTotalResetsDueToWarmReset()
      @JvmName("setTotalResetsDueToWarmReset")
      set(value) {
        _builder.setTotalResetsDueToWarmReset(value)
      }
    /**
     * `uint32 totalResetsDueToWarmReset = 8;`
     */
    public fun clearTotalResetsDueToWarmReset() {
      _builder.clearTotalResetsDueToWarmReset()
    }

    /**
     * `uint32 totalResetsDueToWakeupFromShutdown = 9;`
     */
    public var totalResetsDueToWakeupFromShutdown: kotlin.Int
      @JvmName("getTotalResetsDueToWakeupFromShutdown")
      get() = _builder.getTotalResetsDueToWakeupFromShutdown()
      @JvmName("setTotalResetsDueToWakeupFromShutdown")
      set(value) {
        _builder.setTotalResetsDueToWakeupFromShutdown(value)
      }
    /**
     * `uint32 totalResetsDueToWakeupFromShutdown = 9;`
     */
    public fun clearTotalResetsDueToWakeupFromShutdown() {
      _builder.clearTotalResetsDueToWakeupFromShutdown()
    }

    /**
     * `uint32 totalResetsDueToWakeupFromTCKNoise = 10;`
     */
    public var totalResetsDueToWakeupFromTCKNoise: kotlin.Int
      @JvmName("getTotalResetsDueToWakeupFromTCKNoise")
      get() = _builder.getTotalResetsDueToWakeupFromTCKNoise()
      @JvmName("setTotalResetsDueToWakeupFromTCKNoise")
      set(value) {
        _builder.setTotalResetsDueToWakeupFromTCKNoise(value)
      }
    /**
     * `uint32 totalResetsDueToWakeupFromTCKNoise = 10;`
     */
    public fun clearTotalResetsDueToWakeupFromTCKNoise() {
      _builder.clearTotalResetsDueToWakeupFromTCKNoise()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.teslamotors.protocol.VCSEC.ResetTrackerStats.copy(block: com.teslamotors.protocol.ResetTrackerStatsKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.ResetTrackerStats =
  com.teslamotors.protocol.ResetTrackerStatsKt.Dsl._create(this.toBuilder()).apply { block() }._build()

