// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/VCSECv3.10.14.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.teslamotors.protocol;

@kotlin.jvm.JvmName("-initializesessionInfo")
public inline fun sessionInfo(block: com.teslamotors.protocol.SessionInfoKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.SessionInfo =
  com.teslamotors.protocol.SessionInfoKt.Dsl._create(com.teslamotors.protocol.VCSEC.SessionInfo.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `VCSEC.SessionInfo`
 */
public object SessionInfoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.teslamotors.protocol.VCSEC.SessionInfo.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.teslamotors.protocol.VCSEC.SessionInfo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.teslamotors.protocol.VCSEC.SessionInfo = _builder.build()

    /**
     * `bytes token = 1;`
     */
    public var token: com.google.protobuf.ByteString
      @JvmName("getToken")
      get() = _builder.getToken()
      @JvmName("setToken")
      set(value) {
        _builder.setToken(value)
      }
    /**
     * `bytes token = 1;`
     */
    public fun clearToken() {
      _builder.clearToken()
    }

    /**
     * `uint32 counter = 2;`
     */
    public var counter: kotlin.Int
      @JvmName("getCounter")
      get() = _builder.getCounter()
      @JvmName("setCounter")
      set(value) {
        _builder.setCounter(value)
      }
    /**
     * `uint32 counter = 2;`
     */
    public fun clearCounter() {
      _builder.clearCounter()
    }

    /**
     * `bytes publicKey = 3;`
     */
    public var publicKey: com.google.protobuf.ByteString
      @JvmName("getPublicKey")
      get() = _builder.getPublicKey()
      @JvmName("setPublicKey")
      set(value) {
        _builder.setPublicKey(value)
      }
    /**
     * `bytes publicKey = 3;`
     */
    public fun clearPublicKey() {
      _builder.clearPublicKey()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.teslamotors.protocol.VCSEC.SessionInfo.copy(block: com.teslamotors.protocol.SessionInfoKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.SessionInfo =
  com.teslamotors.protocol.SessionInfoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

