// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/VCSECv3.10.14.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.teslamotors.protocol;

@kotlin.jvm.JvmName("-initializesignedMessageStatus")
public inline fun signedMessageStatus(block: com.teslamotors.protocol.SignedMessage_statusKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.SignedMessage_status =
  com.teslamotors.protocol.SignedMessage_statusKt.Dsl._create(com.teslamotors.protocol.VCSEC.SignedMessage_status.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `VCSEC.SignedMessage_status`
 */
public object SignedMessage_statusKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.teslamotors.protocol.VCSEC.SignedMessage_status.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.teslamotors.protocol.VCSEC.SignedMessage_status.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.teslamotors.protocol.VCSEC.SignedMessage_status = _builder.build()

    /**
     * `uint32 counter = 1;`
     */
    public var counter: kotlin.Int
      @JvmName("getCounter")
      get() = _builder.getCounter()
      @JvmName("setCounter")
      set(value) {
        _builder.setCounter(value)
      }
    /**
     * `uint32 counter = 1;`
     */
    public fun clearCounter() {
      _builder.clearCounter()
    }

    /**
     * `.VCSEC.SignedMessage_information_E signedMessageInformation = 2;`
     */
    public var signedMessageInformation: com.teslamotors.protocol.VCSEC.SignedMessage_information_E
      @JvmName("getSignedMessageInformation")
      get() = _builder.getSignedMessageInformation()
      @JvmName("setSignedMessageInformation")
      set(value) {
        _builder.setSignedMessageInformation(value)
      }
    public var signedMessageInformationValue: kotlin.Int
      @JvmName("getSignedMessageInformationValue")
      get() = _builder.getSignedMessageInformationValue()
      @JvmName("setSignedMessageInformationValue")
      set(value) {
        _builder.setSignedMessageInformationValue(value)
      }
    /**
     * `.VCSEC.SignedMessage_information_E signedMessageInformation = 2;`
     */
    public fun clearSignedMessageInformation() {
      _builder.clearSignedMessageInformation()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.teslamotors.protocol.VCSEC.SignedMessage_status.copy(block: com.teslamotors.protocol.SignedMessage_statusKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.SignedMessage_status =
  com.teslamotors.protocol.SignedMessage_statusKt.Dsl._create(this.toBuilder()).apply { block() }._build()

