// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/VCSECv3.10.14.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.teslamotors.protocol;

@kotlin.jvm.JvmName("-initializesleepManagerStats")
public inline fun sleepManagerStats(block: com.teslamotors.protocol.SleepManagerStatsKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.SleepManagerStats =
  com.teslamotors.protocol.SleepManagerStatsKt.Dsl._create(com.teslamotors.protocol.VCSEC.SleepManagerStats.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `VCSEC.SleepManagerStats`
 */
public object SleepManagerStatsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.teslamotors.protocol.VCSEC.SleepManagerStats.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.teslamotors.protocol.VCSEC.SleepManagerStats.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.teslamotors.protocol.VCSEC.SleepManagerStats = _builder.build()

    /**
     * `uint32 totalCPUTime = 1;`
     */
    public var totalCPUTime: kotlin.Int
      @JvmName("getTotalCPUTime")
      get() = _builder.getTotalCPUTime()
      @JvmName("setTotalCPUTime")
      set(value) {
        _builder.setTotalCPUTime(value)
      }
    /**
     * `uint32 totalCPUTime = 1;`
     */
    public fun clearTotalCPUTime() {
      _builder.clearTotalCPUTime()
    }

    /**
     * `uint32 totalAwakeTime = 2;`
     */
    public var totalAwakeTime: kotlin.Int
      @JvmName("getTotalAwakeTime")
      get() = _builder.getTotalAwakeTime()
      @JvmName("setTotalAwakeTime")
      set(value) {
        _builder.setTotalAwakeTime(value)
      }
    /**
     * `uint32 totalAwakeTime = 2;`
     */
    public fun clearTotalAwakeTime() {
      _builder.clearTotalAwakeTime()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.teslamotors.protocol.VCSEC.SleepManagerStats.copy(block: com.teslamotors.protocol.SleepManagerStatsKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.SleepManagerStats =
  com.teslamotors.protocol.SleepManagerStatsKt.Dsl._create(this.toBuilder()).apply { block() }._build()

