// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/VCSECv3.10.14.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.teslamotors.protocol;

@kotlin.jvm.JvmName("-initializestageBlock")
public inline fun stageBlock(block: com.teslamotors.protocol.StageBlockKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.StageBlock =
  com.teslamotors.protocol.StageBlockKt.Dsl._create(com.teslamotors.protocol.VCSEC.StageBlock.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `VCSEC.StageBlock`
 */
public object StageBlockKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.teslamotors.protocol.VCSEC.StageBlock.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.teslamotors.protocol.VCSEC.StageBlock.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.teslamotors.protocol.VCSEC.StageBlock = _builder.build()

    /**
     * `uint32 blockAddress = 1;`
     */
    public var blockAddress: kotlin.Int
      @JvmName("getBlockAddress")
      get() = _builder.getBlockAddress()
      @JvmName("setBlockAddress")
      set(value) {
        _builder.setBlockAddress(value)
      }
    /**
     * `uint32 blockAddress = 1;`
     */
    public fun clearBlockAddress() {
      _builder.clearBlockAddress()
    }

    /**
     * `bytes blockToStage = 2;`
     */
    public var blockToStage: com.google.protobuf.ByteString
      @JvmName("getBlockToStage")
      get() = _builder.getBlockToStage()
      @JvmName("setBlockToStage")
      set(value) {
        _builder.setBlockToStage(value)
      }
    /**
     * `bytes blockToStage = 2;`
     */
    public fun clearBlockToStage() {
      _builder.clearBlockToStage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.teslamotors.protocol.VCSEC.StageBlock.copy(block: com.teslamotors.protocol.StageBlockKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.StageBlock =
  com.teslamotors.protocol.StageBlockKt.Dsl._create(this.toBuilder()).apply { block() }._build()

