// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/VCSECv3.10.14.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.teslamotors.protocol;

@kotlin.jvm.JvmName("-initializetoKeyfobMessage")
public inline fun toKeyfobMessage(block: com.teslamotors.protocol.ToKeyfobMessageKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.ToKeyfobMessage =
  com.teslamotors.protocol.ToKeyfobMessageKt.Dsl._create(com.teslamotors.protocol.VCSEC.ToKeyfobMessage.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `VCSEC.ToKeyfobMessage`
 */
public object ToKeyfobMessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.teslamotors.protocol.VCSEC.ToKeyfobMessage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.teslamotors.protocol.VCSEC.ToKeyfobMessage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.teslamotors.protocol.VCSEC.ToKeyfobMessage = _builder.build()

    /**
     * `.VCSEC.AuthenticationRequest authenticationRequest = 3;`
     */
    public var authenticationRequest: com.teslamotors.protocol.VCSEC.AuthenticationRequest
      @JvmName("getAuthenticationRequest")
      get() = _builder.getAuthenticationRequest()
      @JvmName("setAuthenticationRequest")
      set(value) {
        _builder.setAuthenticationRequest(value)
      }
    /**
     * `.VCSEC.AuthenticationRequest authenticationRequest = 3;`
     */
    public fun clearAuthenticationRequest() {
      _builder.clearAuthenticationRequest()
    }
    /**
     * `.VCSEC.AuthenticationRequest authenticationRequest = 3;`
     * @return Whether the authenticationRequest field is set.
     */
    public fun hasAuthenticationRequest(): kotlin.Boolean {
      return _builder.hasAuthenticationRequest()
    }

    /**
     * `.VCSEC.UpdaterCommand updaterCommand = 30;`
     */
    public var updaterCommand: com.teslamotors.protocol.VCSEC.UpdaterCommand
      @JvmName("getUpdaterCommand")
      get() = _builder.getUpdaterCommand()
      @JvmName("setUpdaterCommand")
      set(value) {
        _builder.setUpdaterCommand(value)
      }
    /**
     * `.VCSEC.UpdaterCommand updaterCommand = 30;`
     */
    public fun clearUpdaterCommand() {
      _builder.clearUpdaterCommand()
    }
    /**
     * `.VCSEC.UpdaterCommand updaterCommand = 30;`
     * @return Whether the updaterCommand field is set.
     */
    public fun hasUpdaterCommand(): kotlin.Boolean {
      return _builder.hasUpdaterCommand()
    }

    /**
     * `.VCSEC.GenealogyRequest_E genealogyRequest = 31;`
     */
    public var genealogyRequest: com.teslamotors.protocol.VCSEC.GenealogyRequest_E
      @JvmName("getGenealogyRequest")
      get() = _builder.getGenealogyRequest()
      @JvmName("setGenealogyRequest")
      set(value) {
        _builder.setGenealogyRequest(value)
      }
    public var genealogyRequestValue: kotlin.Int
      @JvmName("getGenealogyRequestValue")
      get() = _builder.getGenealogyRequestValue()
      @JvmName("setGenealogyRequestValue")
      set(value) {
        _builder.setGenealogyRequestValue(value)
      }
    /**
     * `.VCSEC.GenealogyRequest_E genealogyRequest = 31;`
     */
    public fun clearGenealogyRequest() {
      _builder.clearGenealogyRequest()
    }
    /**
     * `.VCSEC.GenealogyRequest_E genealogyRequest = 31;`
     * @return Whether the genealogyRequest field is set.
     */
    public fun hasGenealogyRequest(): kotlin.Boolean {
      return _builder.hasGenealogyRequest()
    }

    /**
     * `.VCSEC.SleepManagerRequest sleepManagerRequest = 32;`
     */
    public var sleepManagerRequest: com.teslamotors.protocol.VCSEC.SleepManagerRequest
      @JvmName("getSleepManagerRequest")
      get() = _builder.getSleepManagerRequest()
      @JvmName("setSleepManagerRequest")
      set(value) {
        _builder.setSleepManagerRequest(value)
      }
    /**
     * `.VCSEC.SleepManagerRequest sleepManagerRequest = 32;`
     */
    public fun clearSleepManagerRequest() {
      _builder.clearSleepManagerRequest()
    }
    /**
     * `.VCSEC.SleepManagerRequest sleepManagerRequest = 32;`
     * @return Whether the sleepManagerRequest field is set.
     */
    public fun hasSleepManagerRequest(): kotlin.Boolean {
      return _builder.hasSleepManagerRequest()
    }

    /**
     * `.VCSEC.IMURequest_E imuRequest = 33;`
     */
    public var imuRequest: com.teslamotors.protocol.VCSEC.IMURequest_E
      @JvmName("getImuRequest")
      get() = _builder.getImuRequest()
      @JvmName("setImuRequest")
      set(value) {
        _builder.setImuRequest(value)
      }
    public var imuRequestValue: kotlin.Int
      @JvmName("getImuRequestValue")
      get() = _builder.getImuRequestValue()
      @JvmName("setImuRequestValue")
      set(value) {
        _builder.setImuRequestValue(value)
      }
    /**
     * `.VCSEC.IMURequest_E imuRequest = 33;`
     */
    public fun clearImuRequest() {
      _builder.clearImuRequest()
    }
    /**
     * `.VCSEC.IMURequest_E imuRequest = 33;`
     * @return Whether the imuRequest field is set.
     */
    public fun hasImuRequest(): kotlin.Boolean {
      return _builder.hasImuRequest()
    }

    /**
     * `.VCSEC.NFCSERequest_E nfcseRequest = 34;`
     */
    public var nfcseRequest: com.teslamotors.protocol.VCSEC.NFCSERequest_E
      @JvmName("getNfcseRequest")
      get() = _builder.getNfcseRequest()
      @JvmName("setNfcseRequest")
      set(value) {
        _builder.setNfcseRequest(value)
      }
    public var nfcseRequestValue: kotlin.Int
      @JvmName("getNfcseRequestValue")
      get() = _builder.getNfcseRequestValue()
      @JvmName("setNfcseRequestValue")
      set(value) {
        _builder.setNfcseRequestValue(value)
      }
    /**
     * `.VCSEC.NFCSERequest_E nfcseRequest = 34;`
     */
    public fun clearNfcseRequest() {
      _builder.clearNfcseRequest()
    }
    /**
     * `.VCSEC.NFCSERequest_E nfcseRequest = 34;`
     * @return Whether the nfcseRequest field is set.
     */
    public fun hasNfcseRequest(): kotlin.Boolean {
      return _builder.hasNfcseRequest()
    }
    public val subMessageCase: com.teslamotors.protocol.VCSEC.ToKeyfobMessage.SubMessageCase
      @JvmName("getSubMessageCase")
      get() = _builder.getSubMessageCase()

    public fun clearSubMessage() {
      _builder.clearSubMessage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.teslamotors.protocol.VCSEC.ToKeyfobMessage.copy(block: com.teslamotors.protocol.ToKeyfobMessageKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.ToKeyfobMessage =
  com.teslamotors.protocol.ToKeyfobMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.teslamotors.protocol.VCSEC.ToKeyfobMessageOrBuilder.authenticationRequestOrNull: com.teslamotors.protocol.VCSEC.AuthenticationRequest?
  get() = if (hasAuthenticationRequest()) getAuthenticationRequest() else null

public val com.teslamotors.protocol.VCSEC.ToKeyfobMessageOrBuilder.updaterCommandOrNull: com.teslamotors.protocol.VCSEC.UpdaterCommand?
  get() = if (hasUpdaterCommand()) getUpdaterCommand() else null

public val com.teslamotors.protocol.VCSEC.ToKeyfobMessageOrBuilder.sleepManagerRequestOrNull: com.teslamotors.protocol.VCSEC.SleepManagerRequest?
  get() = if (hasSleepManagerRequest()) getSleepManagerRequest() else null

