// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/VCSECv3.10.14.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.teslamotors.protocol;

@kotlin.jvm.JvmName("-initializetPData")
public inline fun tPData(block: com.teslamotors.protocol.TPDataKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.TPData =
  com.teslamotors.protocol.TPDataKt.Dsl._create(com.teslamotors.protocol.VCSEC.TPData.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `VCSEC.TPData`
 */
public object TPDataKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.teslamotors.protocol.VCSEC.TPData.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.teslamotors.protocol.VCSEC.TPData.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.teslamotors.protocol.VCSEC.TPData = _builder.build()

    /**
     * `int32 pressure = 1;`
     */
    public var pressure: kotlin.Int
      @JvmName("getPressure")
      get() = _builder.getPressure()
      @JvmName("setPressure")
      set(value) {
        _builder.setPressure(value)
      }
    /**
     * `int32 pressure = 1;`
     */
    public fun clearPressure() {
      _builder.clearPressure()
    }

    /**
     * `sint32 temperature = 2;`
     */
    public var temperature: kotlin.Int
      @JvmName("getTemperature")
      get() = _builder.getTemperature()
      @JvmName("setTemperature")
      set(value) {
        _builder.setTemperature(value)
      }
    /**
     * `sint32 temperature = 2;`
     */
    public fun clearTemperature() {
      _builder.clearTemperature()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.teslamotors.protocol.VCSEC.TPData.copy(block: com.teslamotors.protocol.TPDataKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.TPData =
  com.teslamotors.protocol.TPDataKt.Dsl._create(this.toBuilder()).apply { block() }._build()

