// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/VCSECv3.10.14.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.teslamotors.protocol;

@kotlin.jvm.JvmName("-initializetPMotionConfig")
public inline fun tPMotionConfig(block: com.teslamotors.protocol.TPMotionConfigKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.TPMotionConfig =
  com.teslamotors.protocol.TPMotionConfigKt.Dsl._create(com.teslamotors.protocol.VCSEC.TPMotionConfig.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `VCSEC.TPMotionConfig`
 */
public object TPMotionConfigKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.teslamotors.protocol.VCSEC.TPMotionConfig.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.teslamotors.protocol.VCSEC.TPMotionConfig.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.teslamotors.protocol.VCSEC.TPMotionConfig = _builder.build()

    /**
     * `uint32 pressureDelta = 1;`
     */
    public var pressureDelta: kotlin.Int
      @JvmName("getPressureDelta")
      get() = _builder.getPressureDelta()
      @JvmName("setPressureDelta")
      set(value) {
        _builder.setPressureDelta(value)
      }
    /**
     * `uint32 pressureDelta = 1;`
     */
    public fun clearPressureDelta() {
      _builder.clearPressureDelta()
    }

    /**
     * `uint32 temperatureDelta = 2;`
     */
    public var temperatureDelta: kotlin.Int
      @JvmName("getTemperatureDelta")
      get() = _builder.getTemperatureDelta()
      @JvmName("setTemperatureDelta")
      set(value) {
        _builder.setTemperatureDelta(value)
      }
    /**
     * `uint32 temperatureDelta = 2;`
     */
    public fun clearTemperatureDelta() {
      _builder.clearTemperatureDelta()
    }

    /**
     * `.VCSEC.MLXWakePeriod_E PTMeasurePeriod = 3;`
     */
    public var pTMeasurePeriod: com.teslamotors.protocol.VCSEC.MLXWakePeriod_E
      @JvmName("getPTMeasurePeriod")
      get() = _builder.getPTMeasurePeriod()
      @JvmName("setPTMeasurePeriod")
      set(value) {
        _builder.setPTMeasurePeriod(value)
      }
    public var pTMeasurePeriodValue: kotlin.Int
      @JvmName("getPTMeasurePeriodValue")
      get() = _builder.getPTMeasurePeriodValue()
      @JvmName("setPTMeasurePeriodValue")
      set(value) {
        _builder.setPTMeasurePeriodValue(value)
      }
    /**
     * `.VCSEC.MLXWakePeriod_E PTMeasurePeriod = 3;`
     */
    public fun clearPTMeasurePeriod() {
      _builder.clearPTMeasurePeriod()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.teslamotors.protocol.VCSEC.TPMotionConfig.copy(block: com.teslamotors.protocol.TPMotionConfigKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.TPMotionConfig =
  com.teslamotors.protocol.TPMotionConfigKt.Dsl._create(this.toBuilder()).apply { block() }._build()

