// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/VCSECv3.10.14.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.teslamotors.protocol;

@kotlin.jvm.JvmName("-initializetPNotifyTrackerStats")
public inline fun tPNotifyTrackerStats(block: com.teslamotors.protocol.TPNotifyTrackerStatsKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.TPNotifyTrackerStats =
  com.teslamotors.protocol.TPNotifyTrackerStatsKt.Dsl._create(com.teslamotors.protocol.VCSEC.TPNotifyTrackerStats.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `VCSEC.TPNotifyTrackerStats`
 */
public object TPNotifyTrackerStatsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.teslamotors.protocol.VCSEC.TPNotifyTrackerStats.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.teslamotors.protocol.VCSEC.TPNotifyTrackerStats.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.teslamotors.protocol.VCSEC.TPNotifyTrackerStats = _builder.build()

    /**
     * `uint32 notifyReasonUnknownCount = 1;`
     */
    public var notifyReasonUnknownCount: kotlin.Int
      @JvmName("getNotifyReasonUnknownCount")
      get() = _builder.getNotifyReasonUnknownCount()
      @JvmName("setNotifyReasonUnknownCount")
      set(value) {
        _builder.setNotifyReasonUnknownCount(value)
      }
    /**
     * `uint32 notifyReasonUnknownCount = 1;`
     */
    public fun clearNotifyReasonUnknownCount() {
      _builder.clearNotifyReasonUnknownCount()
    }

    /**
     * `uint32 notifyReasonLowPressureCount = 2;`
     */
    public var notifyReasonLowPressureCount: kotlin.Int
      @JvmName("getNotifyReasonLowPressureCount")
      get() = _builder.getNotifyReasonLowPressureCount()
      @JvmName("setNotifyReasonLowPressureCount")
      set(value) {
        _builder.setNotifyReasonLowPressureCount(value)
      }
    /**
     * `uint32 notifyReasonLowPressureCount = 2;`
     */
    public fun clearNotifyReasonLowPressureCount() {
      _builder.clearNotifyReasonLowPressureCount()
    }

    /**
     * `uint32 notifyReasonPTValueUpdateCount = 3;`
     */
    public var notifyReasonPTValueUpdateCount: kotlin.Int
      @JvmName("getNotifyReasonPTValueUpdateCount")
      get() = _builder.getNotifyReasonPTValueUpdateCount()
      @JvmName("setNotifyReasonPTValueUpdateCount")
      set(value) {
        _builder.setNotifyReasonPTValueUpdateCount(value)
      }
    /**
     * `uint32 notifyReasonPTValueUpdateCount = 3;`
     */
    public fun clearNotifyReasonPTValueUpdateCount() {
      _builder.clearNotifyReasonPTValueUpdateCount()
    }

    /**
     * `uint32 notifyReasonWheelMovingCount = 4;`
     */
    public var notifyReasonWheelMovingCount: kotlin.Int
      @JvmName("getNotifyReasonWheelMovingCount")
      get() = _builder.getNotifyReasonWheelMovingCount()
      @JvmName("setNotifyReasonWheelMovingCount")
      set(value) {
        _builder.setNotifyReasonWheelMovingCount(value)
      }
    /**
     * `uint32 notifyReasonWheelMovingCount = 4;`
     */
    public fun clearNotifyReasonWheelMovingCount() {
      _builder.clearNotifyReasonWheelMovingCount()
    }

    /**
     * `uint32 notifyReasonWheelRotationDirectionReadyCount = 5;`
     */
    public var notifyReasonWheelRotationDirectionReadyCount: kotlin.Int
      @JvmName("getNotifyReasonWheelRotationDirectionReadyCount")
      get() = _builder.getNotifyReasonWheelRotationDirectionReadyCount()
      @JvmName("setNotifyReasonWheelRotationDirectionReadyCount")
      set(value) {
        _builder.setNotifyReasonWheelRotationDirectionReadyCount(value)
      }
    /**
     * `uint32 notifyReasonWheelRotationDirectionReadyCount = 5;`
     */
    public fun clearNotifyReasonWheelRotationDirectionReadyCount() {
      _builder.clearNotifyReasonWheelRotationDirectionReadyCount()
    }

    /**
     * `uint32 notifyReasonLFCount = 6;`
     */
    public var notifyReasonLFCount: kotlin.Int
      @JvmName("getNotifyReasonLFCount")
      get() = _builder.getNotifyReasonLFCount()
      @JvmName("setNotifyReasonLFCount")
      set(value) {
        _builder.setNotifyReasonLFCount(value)
      }
    /**
     * `uint32 notifyReasonLFCount = 6;`
     */
    public fun clearNotifyReasonLFCount() {
      _builder.clearNotifyReasonLFCount()
    }

    /**
     * `uint32 notifyReasonFaultCount = 7;`
     */
    public var notifyReasonFaultCount: kotlin.Int
      @JvmName("getNotifyReasonFaultCount")
      get() = _builder.getNotifyReasonFaultCount()
      @JvmName("setNotifyReasonFaultCount")
      set(value) {
        _builder.setNotifyReasonFaultCount(value)
      }
    /**
     * `uint32 notifyReasonFaultCount = 7;`
     */
    public fun clearNotifyReasonFaultCount() {
      _builder.clearNotifyReasonFaultCount()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.teslamotors.protocol.VCSEC.TPNotifyTrackerStats.copy(block: com.teslamotors.protocol.TPNotifyTrackerStatsKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.TPNotifyTrackerStats =
  com.teslamotors.protocol.TPNotifyTrackerStatsKt.Dsl._create(this.toBuilder()).apply { block() }._build()

