// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/VCSECv3.10.14.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.teslamotors.protocol;

@kotlin.jvm.JvmName("-initializetPWheelUnitInfo")
public inline fun tPWheelUnitInfo(block: com.teslamotors.protocol.TPWheelUnitInfoKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.TPWheelUnitInfo =
  com.teslamotors.protocol.TPWheelUnitInfoKt.Dsl._create(com.teslamotors.protocol.VCSEC.TPWheelUnitInfo.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `VCSEC.TPWheelUnitInfo`
 */
public object TPWheelUnitInfoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.teslamotors.protocol.VCSEC.TPWheelUnitInfo.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.teslamotors.protocol.VCSEC.TPWheelUnitInfo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.teslamotors.protocol.VCSEC.TPWheelUnitInfo = _builder.build()

    /**
     * `bytes TIAppCRC = 1;`
     */
    public var tIAppCRC: com.google.protobuf.ByteString
      @JvmName("getTIAppCRC")
      get() = _builder.getTIAppCRC()
      @JvmName("setTIAppCRC")
      set(value) {
        _builder.setTIAppCRC(value)
      }
    /**
     * `bytes TIAppCRC = 1;`
     */
    public fun clearTIAppCRC() {
      _builder.clearTIAppCRC()
    }

    /**
     * `bytes MLXAppCRC = 2;`
     */
    public var mLXAppCRC: com.google.protobuf.ByteString
      @JvmName("getMLXAppCRC")
      get() = _builder.getMLXAppCRC()
      @JvmName("setMLXAppCRC")
      set(value) {
        _builder.setMLXAppCRC(value)
      }
    /**
     * `bytes MLXAppCRC = 2;`
     */
    public fun clearMLXAppCRC() {
      _builder.clearMLXAppCRC()
    }

    /**
     * `uint32 batteryVoltage_mV = 3;`
     */
    public var batteryVoltageMV: kotlin.Int
      @JvmName("getBatteryVoltageMV")
      get() = _builder.getBatteryVoltageMV()
      @JvmName("setBatteryVoltageMV")
      set(value) {
        _builder.setBatteryVoltageMV(value)
      }
    /**
     * `uint32 batteryVoltage_mV = 3;`
     */
    public fun clearBatteryVoltageMV() {
      _builder.clearBatteryVoltageMV()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.teslamotors.protocol.VCSEC.TPWheelUnitInfo.copy(block: com.teslamotors.protocol.TPWheelUnitInfoKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.TPWheelUnitInfo =
  com.teslamotors.protocol.TPWheelUnitInfoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

