// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/VCSECv3.10.14.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.teslamotors.protocol;

@kotlin.jvm.JvmName("-initializeunknownKeyInfo")
public inline fun unknownKeyInfo(block: com.teslamotors.protocol.UnknownKeyInfoKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.UnknownKeyInfo =
  com.teslamotors.protocol.UnknownKeyInfoKt.Dsl._create(com.teslamotors.protocol.VCSEC.UnknownKeyInfo.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `VCSEC.UnknownKeyInfo`
 */
public object UnknownKeyInfoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.teslamotors.protocol.VCSEC.UnknownKeyInfo.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.teslamotors.protocol.VCSEC.UnknownKeyInfo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.teslamotors.protocol.VCSEC.UnknownKeyInfo = _builder.build()

    /**
     * `.VCSEC.KeyStatus keyStatus = 1;`
     */
    public var keyStatus: com.teslamotors.protocol.VCSEC.KeyStatus
      @JvmName("getKeyStatus")
      get() = _builder.getKeyStatus()
      @JvmName("setKeyStatus")
      set(value) {
        _builder.setKeyStatus(value)
      }
    /**
     * `.VCSEC.KeyStatus keyStatus = 1;`
     */
    public fun clearKeyStatus() {
      _builder.clearKeyStatus()
    }
    /**
     * `.VCSEC.KeyStatus keyStatus = 1;`
     * @return Whether the keyStatus field is set.
     */
    public fun hasKeyStatus(): kotlin.Boolean {
      return _builder.hasKeyStatus()
    }

    /**
     * `.VCSEC.PublicKey publicKey = 2;`
     */
    public var publicKey: com.teslamotors.protocol.VCSEC.PublicKey
      @JvmName("getPublicKey")
      get() = _builder.getPublicKey()
      @JvmName("setPublicKey")
      set(value) {
        _builder.setPublicKey(value)
      }
    /**
     * `.VCSEC.PublicKey publicKey = 2;`
     */
    public fun clearPublicKey() {
      _builder.clearPublicKey()
    }
    /**
     * `.VCSEC.PublicKey publicKey = 2;`
     * @return Whether the publicKey field is set.
     */
    public fun hasPublicKey(): kotlin.Boolean {
      return _builder.hasPublicKey()
    }

    /**
     * `.VCSEC.KeyFormFactor keyFormFactor = 3;`
     */
    public var keyFormFactor: com.teslamotors.protocol.VCSEC.KeyFormFactor
      @JvmName("getKeyFormFactor")
      get() = _builder.getKeyFormFactor()
      @JvmName("setKeyFormFactor")
      set(value) {
        _builder.setKeyFormFactor(value)
      }
    public var keyFormFactorValue: kotlin.Int
      @JvmName("getKeyFormFactorValue")
      get() = _builder.getKeyFormFactorValue()
      @JvmName("setKeyFormFactorValue")
      set(value) {
        _builder.setKeyFormFactorValue(value)
      }
    /**
     * `.VCSEC.KeyFormFactor keyFormFactor = 3;`
     */
    public fun clearKeyFormFactor() {
      _builder.clearKeyFormFactor()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.teslamotors.protocol.VCSEC.UnknownKeyInfo.copy(block: com.teslamotors.protocol.UnknownKeyInfoKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.UnknownKeyInfo =
  com.teslamotors.protocol.UnknownKeyInfoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.teslamotors.protocol.VCSEC.UnknownKeyInfoOrBuilder.keyStatusOrNull: com.teslamotors.protocol.VCSEC.KeyStatus?
  get() = if (hasKeyStatus()) getKeyStatus() else null

public val com.teslamotors.protocol.VCSEC.UnknownKeyInfoOrBuilder.publicKeyOrNull: com.teslamotors.protocol.VCSEC.PublicKey?
  get() = if (hasPublicKey()) getPublicKey() else null

