// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/VCSECv3.10.14.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.teslamotors.protocol;

@kotlin.jvm.JvmName("-initializeunsignedMessage")
public inline fun unsignedMessage(block: com.teslamotors.protocol.UnsignedMessageKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.UnsignedMessage =
  com.teslamotors.protocol.UnsignedMessageKt.Dsl._create(com.teslamotors.protocol.VCSEC.UnsignedMessage.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `VCSEC.UnsignedMessage`
 */
public object UnsignedMessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.teslamotors.protocol.VCSEC.UnsignedMessage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.teslamotors.protocol.VCSEC.UnsignedMessage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.teslamotors.protocol.VCSEC.UnsignedMessage = _builder.build()

    /**
     * `.VCSEC.PersonalizationInformation personalizationInformation = 25;`
     */
    public var personalizationInformation: com.teslamotors.protocol.VCSEC.PersonalizationInformation
      @JvmName("getPersonalizationInformation")
      get() = _builder.getPersonalizationInformation()
      @JvmName("setPersonalizationInformation")
      set(value) {
        _builder.setPersonalizationInformation(value)
      }
    /**
     * `.VCSEC.PersonalizationInformation personalizationInformation = 25;`
     */
    public fun clearPersonalizationInformation() {
      _builder.clearPersonalizationInformation()
    }
    /**
     * `.VCSEC.PersonalizationInformation personalizationInformation = 25;`
     * @return Whether the personalizationInformation field is set.
     */
    public fun hasPersonalizationInformation(): kotlin.Boolean {
      return _builder.hasPersonalizationInformation()
    }

    /**
     * `.VCSEC.InformationRequest InformationRequest = 1;`
     */
    public var informationRequest: com.teslamotors.protocol.VCSEC.InformationRequest
      @JvmName("getInformationRequest")
      get() = _builder.getInformationRequest()
      @JvmName("setInformationRequest")
      set(value) {
        _builder.setInformationRequest(value)
      }
    /**
     * `.VCSEC.InformationRequest InformationRequest = 1;`
     */
    public fun clearInformationRequest() {
      _builder.clearInformationRequest()
    }
    /**
     * `.VCSEC.InformationRequest InformationRequest = 1;`
     * @return Whether the informationRequest field is set.
     */
    public fun hasInformationRequest(): kotlin.Boolean {
      return _builder.hasInformationRequest()
    }

    /**
     * `.VCSEC.RKEAction_E RKEAction = 2;`
     */
    public var rKEAction: com.teslamotors.protocol.VCSEC.RKEAction_E
      @JvmName("getRKEAction")
      get() = _builder.getRKEAction()
      @JvmName("setRKEAction")
      set(value) {
        _builder.setRKEAction(value)
      }
    public var rKEActionValue: kotlin.Int
      @JvmName("getRKEActionValue")
      get() = _builder.getRKEActionValue()
      @JvmName("setRKEActionValue")
      set(value) {
        _builder.setRKEActionValue(value)
      }
    /**
     * `.VCSEC.RKEAction_E RKEAction = 2;`
     */
    public fun clearRKEAction() {
      _builder.clearRKEAction()
    }
    /**
     * `.VCSEC.RKEAction_E RKEAction = 2;`
     * @return Whether the rKEAction field is set.
     */
    public fun hasRKEAction(): kotlin.Boolean {
      return _builder.hasRKEAction()
    }

    /**
     * `.VCSEC.AuthenticationResponse authenticationResponse = 3;`
     */
    public var authenticationResponse: com.teslamotors.protocol.VCSEC.AuthenticationResponse
      @JvmName("getAuthenticationResponse")
      get() = _builder.getAuthenticationResponse()
      @JvmName("setAuthenticationResponse")
      set(value) {
        _builder.setAuthenticationResponse(value)
      }
    /**
     * `.VCSEC.AuthenticationResponse authenticationResponse = 3;`
     */
    public fun clearAuthenticationResponse() {
      _builder.clearAuthenticationResponse()
    }
    /**
     * `.VCSEC.AuthenticationResponse authenticationResponse = 3;`
     * @return Whether the authenticationResponse field is set.
     */
    public fun hasAuthenticationResponse(): kotlin.Boolean {
      return _builder.hasAuthenticationResponse()
    }

    /**
     * `.VCSEC.WhitelistOperation WhitelistOperation = 16;`
     */
    public var whitelistOperation: com.teslamotors.protocol.VCSEC.WhitelistOperation
      @JvmName("getWhitelistOperation")
      get() = _builder.getWhitelistOperation()
      @JvmName("setWhitelistOperation")
      set(value) {
        _builder.setWhitelistOperation(value)
      }
    /**
     * `.VCSEC.WhitelistOperation WhitelistOperation = 16;`
     */
    public fun clearWhitelistOperation() {
      _builder.clearWhitelistOperation()
    }
    /**
     * `.VCSEC.WhitelistOperation WhitelistOperation = 16;`
     * @return Whether the whitelistOperation field is set.
     */
    public fun hasWhitelistOperation(): kotlin.Boolean {
      return _builder.hasWhitelistOperation()
    }

    /**
     * `.VCSEC.UpdaterResponse updaterResponse = 20;`
     */
    public var updaterResponse: com.teslamotors.protocol.VCSEC.UpdaterResponse
      @JvmName("getUpdaterResponse")
      get() = _builder.getUpdaterResponse()
      @JvmName("setUpdaterResponse")
      set(value) {
        _builder.setUpdaterResponse(value)
      }
    /**
     * `.VCSEC.UpdaterResponse updaterResponse = 20;`
     */
    public fun clearUpdaterResponse() {
      _builder.clearUpdaterResponse()
    }
    /**
     * `.VCSEC.UpdaterResponse updaterResponse = 20;`
     * @return Whether the updaterResponse field is set.
     */
    public fun hasUpdaterResponse(): kotlin.Boolean {
      return _builder.hasUpdaterResponse()
    }

    /**
     * `.VCSEC.GenealogyResponse genealogyResponse = 21;`
     */
    public var genealogyResponse: com.teslamotors.protocol.VCSEC.GenealogyResponse
      @JvmName("getGenealogyResponse")
      get() = _builder.getGenealogyResponse()
      @JvmName("setGenealogyResponse")
      set(value) {
        _builder.setGenealogyResponse(value)
      }
    /**
     * `.VCSEC.GenealogyResponse genealogyResponse = 21;`
     */
    public fun clearGenealogyResponse() {
      _builder.clearGenealogyResponse()
    }
    /**
     * `.VCSEC.GenealogyResponse genealogyResponse = 21;`
     * @return Whether the genealogyResponse field is set.
     */
    public fun hasGenealogyResponse(): kotlin.Boolean {
      return _builder.hasGenealogyResponse()
    }

    /**
     * `.VCSEC.KeyMetadata setMetaDataForKey = 22;`
     */
    public var setMetaDataForKey: com.teslamotors.protocol.VCSEC.KeyMetadata
      @JvmName("getSetMetaDataForKey")
      get() = _builder.getSetMetaDataForKey()
      @JvmName("setSetMetaDataForKey")
      set(value) {
        _builder.setSetMetaDataForKey(value)
      }
    /**
     * `.VCSEC.KeyMetadata setMetaDataForKey = 22;`
     */
    public fun clearSetMetaDataForKey() {
      _builder.clearSetMetaDataForKey()
    }
    /**
     * `.VCSEC.KeyMetadata setMetaDataForKey = 22;`
     * @return Whether the setMetaDataForKey field is set.
     */
    public fun hasSetMetaDataForKey(): kotlin.Boolean {
      return _builder.hasSetMetaDataForKey()
    }

    /**
     * `.VCSEC.KeyfobInfo keyfobInfo = 23;`
     */
    public var keyfobInfo: com.teslamotors.protocol.VCSEC.KeyfobInfo
      @JvmName("getKeyfobInfo")
      get() = _builder.getKeyfobInfo()
      @JvmName("setKeyfobInfo")
      set(value) {
        _builder.setKeyfobInfo(value)
      }
    /**
     * `.VCSEC.KeyfobInfo keyfobInfo = 23;`
     */
    public fun clearKeyfobInfo() {
      _builder.clearKeyfobInfo()
    }
    /**
     * `.VCSEC.KeyfobInfo keyfobInfo = 23;`
     * @return Whether the keyfobInfo field is set.
     */
    public fun hasKeyfobInfo(): kotlin.Boolean {
      return _builder.hasKeyfobInfo()
    }

    /**
     * `.VCSEC.IMUState_E IMUState = 24;`
     */
    public var iMUState: com.teslamotors.protocol.VCSEC.IMUState_E
      @JvmName("getIMUState")
      get() = _builder.getIMUState()
      @JvmName("setIMUState")
      set(value) {
        _builder.setIMUState(value)
      }
    public var iMUStateValue: kotlin.Int
      @JvmName("getIMUStateValue")
      get() = _builder.getIMUStateValue()
      @JvmName("setIMUStateValue")
      set(value) {
        _builder.setIMUStateValue(value)
      }
    /**
     * `.VCSEC.IMUState_E IMUState = 24;`
     */
    public fun clearIMUState() {
      _builder.clearIMUState()
    }
    /**
     * `.VCSEC.IMUState_E IMUState = 24;`
     * @return Whether the iMUState field is set.
     */
    public fun hasIMUState(): kotlin.Boolean {
      return _builder.hasIMUState()
    }

    /**
     * `.VCSEC.NFCSEState nfcseState = 26;`
     */
    public var nfcseState: com.teslamotors.protocol.VCSEC.NFCSEState
      @JvmName("getNfcseState")
      get() = _builder.getNfcseState()
      @JvmName("setNfcseState")
      set(value) {
        _builder.setNfcseState(value)
      }
    /**
     * `.VCSEC.NFCSEState nfcseState = 26;`
     */
    public fun clearNfcseState() {
      _builder.clearNfcseState()
    }
    /**
     * `.VCSEC.NFCSEState nfcseState = 26;`
     * @return Whether the nfcseState field is set.
     */
    public fun hasNfcseState(): kotlin.Boolean {
      return _builder.hasNfcseState()
    }

    /**
     * `.VCSEC.SleepManagerStats lowPowerDeviceSleepManagerStats = 27;`
     */
    public var lowPowerDeviceSleepManagerStats: com.teslamotors.protocol.VCSEC.SleepManagerStats
      @JvmName("getLowPowerDeviceSleepManagerStats")
      get() = _builder.getLowPowerDeviceSleepManagerStats()
      @JvmName("setLowPowerDeviceSleepManagerStats")
      set(value) {
        _builder.setLowPowerDeviceSleepManagerStats(value)
      }
    /**
     * `.VCSEC.SleepManagerStats lowPowerDeviceSleepManagerStats = 27;`
     */
    public fun clearLowPowerDeviceSleepManagerStats() {
      _builder.clearLowPowerDeviceSleepManagerStats()
    }
    /**
     * `.VCSEC.SleepManagerStats lowPowerDeviceSleepManagerStats = 27;`
     * @return Whether the lowPowerDeviceSleepManagerStats field is set.
     */
    public fun hasLowPowerDeviceSleepManagerStats(): kotlin.Boolean {
      return _builder.hasLowPowerDeviceSleepManagerStats()
    }

    /**
     * `.VCSEC.TPData TPData = 28;`
     */
    public var tPData: com.teslamotors.protocol.VCSEC.TPData
      @JvmName("getTPData")
      get() = _builder.getTPData()
      @JvmName("setTPData")
      set(value) {
        _builder.setTPData(value)
      }
    /**
     * `.VCSEC.TPData TPData = 28;`
     */
    public fun clearTPData() {
      _builder.clearTPData()
    }
    /**
     * `.VCSEC.TPData TPData = 28;`
     * @return Whether the tPData field is set.
     */
    public fun hasTPData(): kotlin.Boolean {
      return _builder.hasTPData()
    }

    /**
     * `.VCSEC.TPWheelUnitInfo TPWheelUnitInfo = 29;`
     */
    public var tPWheelUnitInfo: com.teslamotors.protocol.VCSEC.TPWheelUnitInfo
      @JvmName("getTPWheelUnitInfo")
      get() = _builder.getTPWheelUnitInfo()
      @JvmName("setTPWheelUnitInfo")
      set(value) {
        _builder.setTPWheelUnitInfo(value)
      }
    /**
     * `.VCSEC.TPWheelUnitInfo TPWheelUnitInfo = 29;`
     */
    public fun clearTPWheelUnitInfo() {
      _builder.clearTPWheelUnitInfo()
    }
    /**
     * `.VCSEC.TPWheelUnitInfo TPWheelUnitInfo = 29;`
     * @return Whether the tPWheelUnitInfo field is set.
     */
    public fun hasTPWheelUnitInfo(): kotlin.Boolean {
      return _builder.hasTPWheelUnitInfo()
    }

    /**
     * `.VCSEC.ResetTrackerStats resetTrackerStats = 30;`
     */
    public var resetTrackerStats: com.teslamotors.protocol.VCSEC.ResetTrackerStats
      @JvmName("getResetTrackerStats")
      get() = _builder.getResetTrackerStats()
      @JvmName("setResetTrackerStats")
      set(value) {
        _builder.setResetTrackerStats(value)
      }
    /**
     * `.VCSEC.ResetTrackerStats resetTrackerStats = 30;`
     */
    public fun clearResetTrackerStats() {
      _builder.clearResetTrackerStats()
    }
    /**
     * `.VCSEC.ResetTrackerStats resetTrackerStats = 30;`
     * @return Whether the resetTrackerStats field is set.
     */
    public fun hasResetTrackerStats(): kotlin.Boolean {
      return _builder.hasResetTrackerStats()
    }

    /**
     * `.VCSEC.TPNotifyTrackerStats TPNotifyTrackerStats = 31;`
     */
    public var tPNotifyTrackerStats: com.teslamotors.protocol.VCSEC.TPNotifyTrackerStats
      @JvmName("getTPNotifyTrackerStats")
      get() = _builder.getTPNotifyTrackerStats()
      @JvmName("setTPNotifyTrackerStats")
      set(value) {
        _builder.setTPNotifyTrackerStats(value)
      }
    /**
     * `.VCSEC.TPNotifyTrackerStats TPNotifyTrackerStats = 31;`
     */
    public fun clearTPNotifyTrackerStats() {
      _builder.clearTPNotifyTrackerStats()
    }
    /**
     * `.VCSEC.TPNotifyTrackerStats TPNotifyTrackerStats = 31;`
     * @return Whether the tPNotifyTrackerStats field is set.
     */
    public fun hasTPNotifyTrackerStats(): kotlin.Boolean {
      return _builder.hasTPNotifyTrackerStats()
    }

    /**
     * `.VCSEC.TPNewSensorData TPNewSensorData = 32;`
     */
    public var tPNewSensorData: com.teslamotors.protocol.VCSEC.TPNewSensorData
      @JvmName("getTPNewSensorData")
      get() = _builder.getTPNewSensorData()
      @JvmName("setTPNewSensorData")
      set(value) {
        _builder.setTPNewSensorData(value)
      }
    /**
     * `.VCSEC.TPNewSensorData TPNewSensorData = 32;`
     */
    public fun clearTPNewSensorData() {
      _builder.clearTPNewSensorData()
    }
    /**
     * `.VCSEC.TPNewSensorData TPNewSensorData = 32;`
     * @return Whether the tPNewSensorData field is set.
     */
    public fun hasTPNewSensorData(): kotlin.Boolean {
      return _builder.hasTPNewSensorData()
    }

    /**
     * `.VCSEC.TPLRDetection TPLRDetection = 33;`
     */
    public var tPLRDetection: com.teslamotors.protocol.VCSEC.TPLRDetection
      @JvmName("getTPLRDetection")
      get() = _builder.getTPLRDetection()
      @JvmName("setTPLRDetection")
      set(value) {
        _builder.setTPLRDetection(value)
      }
    /**
     * `.VCSEC.TPLRDetection TPLRDetection = 33;`
     */
    public fun clearTPLRDetection() {
      _builder.clearTPLRDetection()
    }
    /**
     * `.VCSEC.TPLRDetection TPLRDetection = 33;`
     * @return Whether the tPLRDetection field is set.
     */
    public fun hasTPLRDetection(): kotlin.Boolean {
      return _builder.hasTPLRDetection()
    }

    /**
     * `.VCSEC.ConnectionMetrics connectionMetrics = 34;`
     */
    public var connectionMetrics: com.teslamotors.protocol.VCSEC.ConnectionMetrics
      @JvmName("getConnectionMetrics")
      get() = _builder.getConnectionMetrics()
      @JvmName("setConnectionMetrics")
      set(value) {
        _builder.setConnectionMetrics(value)
      }
    /**
     * `.VCSEC.ConnectionMetrics connectionMetrics = 34;`
     */
    public fun clearConnectionMetrics() {
      _builder.clearConnectionMetrics()
    }
    /**
     * `.VCSEC.ConnectionMetrics connectionMetrics = 34;`
     * @return Whether the connectionMetrics field is set.
     */
    public fun hasConnectionMetrics(): kotlin.Boolean {
      return _builder.hasConnectionMetrics()
    }

    /**
     * `.VCSEC.Activity_E deviceActivity = 35;`
     */
    public var deviceActivity: com.teslamotors.protocol.VCSEC.Activity_E
      @JvmName("getDeviceActivity")
      get() = _builder.getDeviceActivity()
      @JvmName("setDeviceActivity")
      set(value) {
        _builder.setDeviceActivity(value)
      }
    public var deviceActivityValue: kotlin.Int
      @JvmName("getDeviceActivityValue")
      get() = _builder.getDeviceActivityValue()
      @JvmName("setDeviceActivityValue")
      set(value) {
        _builder.setDeviceActivityValue(value)
      }
    /**
     * `.VCSEC.Activity_E deviceActivity = 35;`
     */
    public fun clearDeviceActivity() {
      _builder.clearDeviceActivity()
    }
    /**
     * `.VCSEC.Activity_E deviceActivity = 35;`
     * @return Whether the deviceActivity field is set.
     */
    public fun hasDeviceActivity(): kotlin.Boolean {
      return _builder.hasDeviceActivity()
    }
    public val subMessageCase: com.teslamotors.protocol.VCSEC.UnsignedMessage.SubMessageCase
      @JvmName("getSubMessageCase")
      get() = _builder.getSubMessageCase()

    public fun clearSubMessage() {
      _builder.clearSubMessage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.teslamotors.protocol.VCSEC.UnsignedMessage.copy(block: com.teslamotors.protocol.UnsignedMessageKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.UnsignedMessage =
  com.teslamotors.protocol.UnsignedMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.teslamotors.protocol.VCSEC.UnsignedMessageOrBuilder.personalizationInformationOrNull: com.teslamotors.protocol.VCSEC.PersonalizationInformation?
  get() = if (hasPersonalizationInformation()) getPersonalizationInformation() else null

public val com.teslamotors.protocol.VCSEC.UnsignedMessageOrBuilder.informationRequestOrNull: com.teslamotors.protocol.VCSEC.InformationRequest?
  get() = if (hasInformationRequest()) getInformationRequest() else null

public val com.teslamotors.protocol.VCSEC.UnsignedMessageOrBuilder.authenticationResponseOrNull: com.teslamotors.protocol.VCSEC.AuthenticationResponse?
  get() = if (hasAuthenticationResponse()) getAuthenticationResponse() else null

public val com.teslamotors.protocol.VCSEC.UnsignedMessageOrBuilder.whitelistOperationOrNull: com.teslamotors.protocol.VCSEC.WhitelistOperation?
  get() = if (hasWhitelistOperation()) getWhitelistOperation() else null

public val com.teslamotors.protocol.VCSEC.UnsignedMessageOrBuilder.updaterResponseOrNull: com.teslamotors.protocol.VCSEC.UpdaterResponse?
  get() = if (hasUpdaterResponse()) getUpdaterResponse() else null

public val com.teslamotors.protocol.VCSEC.UnsignedMessageOrBuilder.genealogyResponseOrNull: com.teslamotors.protocol.VCSEC.GenealogyResponse?
  get() = if (hasGenealogyResponse()) getGenealogyResponse() else null

public val com.teslamotors.protocol.VCSEC.UnsignedMessageOrBuilder.setMetaDataForKeyOrNull: com.teslamotors.protocol.VCSEC.KeyMetadata?
  get() = if (hasSetMetaDataForKey()) getSetMetaDataForKey() else null

public val com.teslamotors.protocol.VCSEC.UnsignedMessageOrBuilder.keyfobInfoOrNull: com.teslamotors.protocol.VCSEC.KeyfobInfo?
  get() = if (hasKeyfobInfo()) getKeyfobInfo() else null

public val com.teslamotors.protocol.VCSEC.UnsignedMessageOrBuilder.nfcseStateOrNull: com.teslamotors.protocol.VCSEC.NFCSEState?
  get() = if (hasNfcseState()) getNfcseState() else null

public val com.teslamotors.protocol.VCSEC.UnsignedMessageOrBuilder.lowPowerDeviceSleepManagerStatsOrNull: com.teslamotors.protocol.VCSEC.SleepManagerStats?
  get() = if (hasLowPowerDeviceSleepManagerStats()) getLowPowerDeviceSleepManagerStats() else null

public val com.teslamotors.protocol.VCSEC.UnsignedMessageOrBuilder.tPDataOrNull: com.teslamotors.protocol.VCSEC.TPData?
  get() = if (hasTPData()) getTPData() else null

public val com.teslamotors.protocol.VCSEC.UnsignedMessageOrBuilder.tPWheelUnitInfoOrNull: com.teslamotors.protocol.VCSEC.TPWheelUnitInfo?
  get() = if (hasTPWheelUnitInfo()) getTPWheelUnitInfo() else null

public val com.teslamotors.protocol.VCSEC.UnsignedMessageOrBuilder.resetTrackerStatsOrNull: com.teslamotors.protocol.VCSEC.ResetTrackerStats?
  get() = if (hasResetTrackerStats()) getResetTrackerStats() else null

public val com.teslamotors.protocol.VCSEC.UnsignedMessageOrBuilder.tPNotifyTrackerStatsOrNull: com.teslamotors.protocol.VCSEC.TPNotifyTrackerStats?
  get() = if (hasTPNotifyTrackerStats()) getTPNotifyTrackerStats() else null

public val com.teslamotors.protocol.VCSEC.UnsignedMessageOrBuilder.tPNewSensorDataOrNull: com.teslamotors.protocol.VCSEC.TPNewSensorData?
  get() = if (hasTPNewSensorData()) getTPNewSensorData() else null

public val com.teslamotors.protocol.VCSEC.UnsignedMessageOrBuilder.tPLRDetectionOrNull: com.teslamotors.protocol.VCSEC.TPLRDetection?
  get() = if (hasTPLRDetection()) getTPLRDetection() else null

public val com.teslamotors.protocol.VCSEC.UnsignedMessageOrBuilder.connectionMetricsOrNull: com.teslamotors.protocol.VCSEC.ConnectionMetrics?
  get() = if (hasConnectionMetrics()) getConnectionMetrics() else null

