// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/VCSECv3.10.14.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.teslamotors.protocol;

@kotlin.jvm.JvmName("-initializeunsignedMessageTPWheelUnit")
public inline fun unsignedMessageTPWheelUnit(block: com.teslamotors.protocol.UnsignedMessageTPWheelUnitKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.UnsignedMessageTPWheelUnit =
  com.teslamotors.protocol.UnsignedMessageTPWheelUnitKt.Dsl._create(com.teslamotors.protocol.VCSEC.UnsignedMessageTPWheelUnit.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `VCSEC.UnsignedMessageTPWheelUnit`
 */
public object UnsignedMessageTPWheelUnitKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.teslamotors.protocol.VCSEC.UnsignedMessageTPWheelUnit.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.teslamotors.protocol.VCSEC.UnsignedMessageTPWheelUnit.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.teslamotors.protocol.VCSEC.UnsignedMessageTPWheelUnit = _builder.build()

    /**
     * `.VCSEC.UpdaterResponse updaterResponse = 20;`
     */
    public var updaterResponse: com.teslamotors.protocol.VCSEC.UpdaterResponse
      @JvmName("getUpdaterResponse")
      get() = _builder.getUpdaterResponse()
      @JvmName("setUpdaterResponse")
      set(value) {
        _builder.setUpdaterResponse(value)
      }
    /**
     * `.VCSEC.UpdaterResponse updaterResponse = 20;`
     */
    public fun clearUpdaterResponse() {
      _builder.clearUpdaterResponse()
    }
    /**
     * `.VCSEC.UpdaterResponse updaterResponse = 20;`
     * @return Whether the updaterResponse field is set.
     */
    public fun hasUpdaterResponse(): kotlin.Boolean {
      return _builder.hasUpdaterResponse()
    }

    /**
     * `.VCSEC.GenealogyResponse genealogyResponse = 21;`
     */
    public var genealogyResponse: com.teslamotors.protocol.VCSEC.GenealogyResponse
      @JvmName("getGenealogyResponse")
      get() = _builder.getGenealogyResponse()
      @JvmName("setGenealogyResponse")
      set(value) {
        _builder.setGenealogyResponse(value)
      }
    /**
     * `.VCSEC.GenealogyResponse genealogyResponse = 21;`
     */
    public fun clearGenealogyResponse() {
      _builder.clearGenealogyResponse()
    }
    /**
     * `.VCSEC.GenealogyResponse genealogyResponse = 21;`
     * @return Whether the genealogyResponse field is set.
     */
    public fun hasGenealogyResponse(): kotlin.Boolean {
      return _builder.hasGenealogyResponse()
    }

    /**
     * `.VCSEC.SleepManagerStats lowPowerDeviceSleepManagerStats = 27;`
     */
    public var lowPowerDeviceSleepManagerStats: com.teslamotors.protocol.VCSEC.SleepManagerStats
      @JvmName("getLowPowerDeviceSleepManagerStats")
      get() = _builder.getLowPowerDeviceSleepManagerStats()
      @JvmName("setLowPowerDeviceSleepManagerStats")
      set(value) {
        _builder.setLowPowerDeviceSleepManagerStats(value)
      }
    /**
     * `.VCSEC.SleepManagerStats lowPowerDeviceSleepManagerStats = 27;`
     */
    public fun clearLowPowerDeviceSleepManagerStats() {
      _builder.clearLowPowerDeviceSleepManagerStats()
    }
    /**
     * `.VCSEC.SleepManagerStats lowPowerDeviceSleepManagerStats = 27;`
     * @return Whether the lowPowerDeviceSleepManagerStats field is set.
     */
    public fun hasLowPowerDeviceSleepManagerStats(): kotlin.Boolean {
      return _builder.hasLowPowerDeviceSleepManagerStats()
    }

    /**
     * `.VCSEC.TPData TPData = 28;`
     */
    public var tPData: com.teslamotors.protocol.VCSEC.TPData
      @JvmName("getTPData")
      get() = _builder.getTPData()
      @JvmName("setTPData")
      set(value) {
        _builder.setTPData(value)
      }
    /**
     * `.VCSEC.TPData TPData = 28;`
     */
    public fun clearTPData() {
      _builder.clearTPData()
    }
    /**
     * `.VCSEC.TPData TPData = 28;`
     * @return Whether the tPData field is set.
     */
    public fun hasTPData(): kotlin.Boolean {
      return _builder.hasTPData()
    }

    /**
     * `.VCSEC.TPWheelUnitInfo TPWheelUnitInfo = 29;`
     */
    public var tPWheelUnitInfo: com.teslamotors.protocol.VCSEC.TPWheelUnitInfo
      @JvmName("getTPWheelUnitInfo")
      get() = _builder.getTPWheelUnitInfo()
      @JvmName("setTPWheelUnitInfo")
      set(value) {
        _builder.setTPWheelUnitInfo(value)
      }
    /**
     * `.VCSEC.TPWheelUnitInfo TPWheelUnitInfo = 29;`
     */
    public fun clearTPWheelUnitInfo() {
      _builder.clearTPWheelUnitInfo()
    }
    /**
     * `.VCSEC.TPWheelUnitInfo TPWheelUnitInfo = 29;`
     * @return Whether the tPWheelUnitInfo field is set.
     */
    public fun hasTPWheelUnitInfo(): kotlin.Boolean {
      return _builder.hasTPWheelUnitInfo()
    }

    /**
     * `.VCSEC.ResetTrackerStats resetTrackerStats = 30;`
     */
    public var resetTrackerStats: com.teslamotors.protocol.VCSEC.ResetTrackerStats
      @JvmName("getResetTrackerStats")
      get() = _builder.getResetTrackerStats()
      @JvmName("setResetTrackerStats")
      set(value) {
        _builder.setResetTrackerStats(value)
      }
    /**
     * `.VCSEC.ResetTrackerStats resetTrackerStats = 30;`
     */
    public fun clearResetTrackerStats() {
      _builder.clearResetTrackerStats()
    }
    /**
     * `.VCSEC.ResetTrackerStats resetTrackerStats = 30;`
     * @return Whether the resetTrackerStats field is set.
     */
    public fun hasResetTrackerStats(): kotlin.Boolean {
      return _builder.hasResetTrackerStats()
    }

    /**
     * `.VCSEC.TPNotifyTrackerStats TPNotifyTrackerStats = 31;`
     */
    public var tPNotifyTrackerStats: com.teslamotors.protocol.VCSEC.TPNotifyTrackerStats
      @JvmName("getTPNotifyTrackerStats")
      get() = _builder.getTPNotifyTrackerStats()
      @JvmName("setTPNotifyTrackerStats")
      set(value) {
        _builder.setTPNotifyTrackerStats(value)
      }
    /**
     * `.VCSEC.TPNotifyTrackerStats TPNotifyTrackerStats = 31;`
     */
    public fun clearTPNotifyTrackerStats() {
      _builder.clearTPNotifyTrackerStats()
    }
    /**
     * `.VCSEC.TPNotifyTrackerStats TPNotifyTrackerStats = 31;`
     * @return Whether the tPNotifyTrackerStats field is set.
     */
    public fun hasTPNotifyTrackerStats(): kotlin.Boolean {
      return _builder.hasTPNotifyTrackerStats()
    }

    /**
     * `.VCSEC.TPNewSensorData TPNewSensorData = 32;`
     */
    public var tPNewSensorData: com.teslamotors.protocol.VCSEC.TPNewSensorData
      @JvmName("getTPNewSensorData")
      get() = _builder.getTPNewSensorData()
      @JvmName("setTPNewSensorData")
      set(value) {
        _builder.setTPNewSensorData(value)
      }
    /**
     * `.VCSEC.TPNewSensorData TPNewSensorData = 32;`
     */
    public fun clearTPNewSensorData() {
      _builder.clearTPNewSensorData()
    }
    /**
     * `.VCSEC.TPNewSensorData TPNewSensorData = 32;`
     * @return Whether the tPNewSensorData field is set.
     */
    public fun hasTPNewSensorData(): kotlin.Boolean {
      return _builder.hasTPNewSensorData()
    }

    /**
     * `.VCSEC.TPLRDetection TPLRDetection = 33;`
     */
    public var tPLRDetection: com.teslamotors.protocol.VCSEC.TPLRDetection
      @JvmName("getTPLRDetection")
      get() = _builder.getTPLRDetection()
      @JvmName("setTPLRDetection")
      set(value) {
        _builder.setTPLRDetection(value)
      }
    /**
     * `.VCSEC.TPLRDetection TPLRDetection = 33;`
     */
    public fun clearTPLRDetection() {
      _builder.clearTPLRDetection()
    }
    /**
     * `.VCSEC.TPLRDetection TPLRDetection = 33;`
     * @return Whether the tPLRDetection field is set.
     */
    public fun hasTPLRDetection(): kotlin.Boolean {
      return _builder.hasTPLRDetection()
    }

    /**
     * `.VCSEC.ConnectionMetrics connectionMetrics = 34;`
     */
    public var connectionMetrics: com.teslamotors.protocol.VCSEC.ConnectionMetrics
      @JvmName("getConnectionMetrics")
      get() = _builder.getConnectionMetrics()
      @JvmName("setConnectionMetrics")
      set(value) {
        _builder.setConnectionMetrics(value)
      }
    /**
     * `.VCSEC.ConnectionMetrics connectionMetrics = 34;`
     */
    public fun clearConnectionMetrics() {
      _builder.clearConnectionMetrics()
    }
    /**
     * `.VCSEC.ConnectionMetrics connectionMetrics = 34;`
     * @return Whether the connectionMetrics field is set.
     */
    public fun hasConnectionMetrics(): kotlin.Boolean {
      return _builder.hasConnectionMetrics()
    }
    public val subMessageCase: com.teslamotors.protocol.VCSEC.UnsignedMessageTPWheelUnit.SubMessageCase
      @JvmName("getSubMessageCase")
      get() = _builder.getSubMessageCase()

    public fun clearSubMessage() {
      _builder.clearSubMessage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.teslamotors.protocol.VCSEC.UnsignedMessageTPWheelUnit.copy(block: com.teslamotors.protocol.UnsignedMessageTPWheelUnitKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.UnsignedMessageTPWheelUnit =
  com.teslamotors.protocol.UnsignedMessageTPWheelUnitKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.teslamotors.protocol.VCSEC.UnsignedMessageTPWheelUnitOrBuilder.updaterResponseOrNull: com.teslamotors.protocol.VCSEC.UpdaterResponse?
  get() = if (hasUpdaterResponse()) getUpdaterResponse() else null

public val com.teslamotors.protocol.VCSEC.UnsignedMessageTPWheelUnitOrBuilder.genealogyResponseOrNull: com.teslamotors.protocol.VCSEC.GenealogyResponse?
  get() = if (hasGenealogyResponse()) getGenealogyResponse() else null

public val com.teslamotors.protocol.VCSEC.UnsignedMessageTPWheelUnitOrBuilder.lowPowerDeviceSleepManagerStatsOrNull: com.teslamotors.protocol.VCSEC.SleepManagerStats?
  get() = if (hasLowPowerDeviceSleepManagerStats()) getLowPowerDeviceSleepManagerStats() else null

public val com.teslamotors.protocol.VCSEC.UnsignedMessageTPWheelUnitOrBuilder.tPDataOrNull: com.teslamotors.protocol.VCSEC.TPData?
  get() = if (hasTPData()) getTPData() else null

public val com.teslamotors.protocol.VCSEC.UnsignedMessageTPWheelUnitOrBuilder.tPWheelUnitInfoOrNull: com.teslamotors.protocol.VCSEC.TPWheelUnitInfo?
  get() = if (hasTPWheelUnitInfo()) getTPWheelUnitInfo() else null

public val com.teslamotors.protocol.VCSEC.UnsignedMessageTPWheelUnitOrBuilder.resetTrackerStatsOrNull: com.teslamotors.protocol.VCSEC.ResetTrackerStats?
  get() = if (hasResetTrackerStats()) getResetTrackerStats() else null

public val com.teslamotors.protocol.VCSEC.UnsignedMessageTPWheelUnitOrBuilder.tPNotifyTrackerStatsOrNull: com.teslamotors.protocol.VCSEC.TPNotifyTrackerStats?
  get() = if (hasTPNotifyTrackerStats()) getTPNotifyTrackerStats() else null

public val com.teslamotors.protocol.VCSEC.UnsignedMessageTPWheelUnitOrBuilder.tPNewSensorDataOrNull: com.teslamotors.protocol.VCSEC.TPNewSensorData?
  get() = if (hasTPNewSensorData()) getTPNewSensorData() else null

public val com.teslamotors.protocol.VCSEC.UnsignedMessageTPWheelUnitOrBuilder.tPLRDetectionOrNull: com.teslamotors.protocol.VCSEC.TPLRDetection?
  get() = if (hasTPLRDetection()) getTPLRDetection() else null

public val com.teslamotors.protocol.VCSEC.UnsignedMessageTPWheelUnitOrBuilder.connectionMetricsOrNull: com.teslamotors.protocol.VCSEC.ConnectionMetrics?
  get() = if (hasConnectionMetrics()) getConnectionMetrics() else null

