// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/VCSECv3.10.14.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.teslamotors.protocol;

@kotlin.jvm.JvmName("-initializeunsignedMessageShort")
public inline fun unsignedMessageShort(block: com.teslamotors.protocol.UnsignedMessageShortKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.UnsignedMessageShort =
  com.teslamotors.protocol.UnsignedMessageShortKt.Dsl._create(com.teslamotors.protocol.VCSEC.UnsignedMessageShort.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `VCSEC.UnsignedMessageShort`
 */
public object UnsignedMessageShortKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.teslamotors.protocol.VCSEC.UnsignedMessageShort.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.teslamotors.protocol.VCSEC.UnsignedMessageShort.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.teslamotors.protocol.VCSEC.UnsignedMessageShort = _builder.build()

    /**
     * `.VCSEC.RKEAction_E RKEAction = 2;`
     */
    public var rKEAction: com.teslamotors.protocol.VCSEC.RKEAction_E
      @JvmName("getRKEAction")
      get() = _builder.getRKEAction()
      @JvmName("setRKEAction")
      set(value) {
        _builder.setRKEAction(value)
      }
    public var rKEActionValue: kotlin.Int
      @JvmName("getRKEActionValue")
      get() = _builder.getRKEActionValue()
      @JvmName("setRKEActionValue")
      set(value) {
        _builder.setRKEActionValue(value)
      }
    /**
     * `.VCSEC.RKEAction_E RKEAction = 2;`
     */
    public fun clearRKEAction() {
      _builder.clearRKEAction()
    }
    /**
     * `.VCSEC.RKEAction_E RKEAction = 2;`
     * @return Whether the rKEAction field is set.
     */
    public fun hasRKEAction(): kotlin.Boolean {
      return _builder.hasRKEAction()
    }

    /**
     * `.VCSEC.AuthenticationResponse authenticationResponse = 3;`
     */
    public var authenticationResponse: com.teslamotors.protocol.VCSEC.AuthenticationResponse
      @JvmName("getAuthenticationResponse")
      get() = _builder.getAuthenticationResponse()
      @JvmName("setAuthenticationResponse")
      set(value) {
        _builder.setAuthenticationResponse(value)
      }
    /**
     * `.VCSEC.AuthenticationResponse authenticationResponse = 3;`
     */
    public fun clearAuthenticationResponse() {
      _builder.clearAuthenticationResponse()
    }
    /**
     * `.VCSEC.AuthenticationResponse authenticationResponse = 3;`
     * @return Whether the authenticationResponse field is set.
     */
    public fun hasAuthenticationResponse(): kotlin.Boolean {
      return _builder.hasAuthenticationResponse()
    }

    /**
     * `.VCSEC.UpdaterResponse updaterResponse = 20;`
     */
    public var updaterResponse: com.teslamotors.protocol.VCSEC.UpdaterResponse
      @JvmName("getUpdaterResponse")
      get() = _builder.getUpdaterResponse()
      @JvmName("setUpdaterResponse")
      set(value) {
        _builder.setUpdaterResponse(value)
      }
    /**
     * `.VCSEC.UpdaterResponse updaterResponse = 20;`
     */
    public fun clearUpdaterResponse() {
      _builder.clearUpdaterResponse()
    }
    /**
     * `.VCSEC.UpdaterResponse updaterResponse = 20;`
     * @return Whether the updaterResponse field is set.
     */
    public fun hasUpdaterResponse(): kotlin.Boolean {
      return _builder.hasUpdaterResponse()
    }

    /**
     * `.VCSEC.GenealogyResponse genealogyResponse = 21;`
     */
    public var genealogyResponse: com.teslamotors.protocol.VCSEC.GenealogyResponse
      @JvmName("getGenealogyResponse")
      get() = _builder.getGenealogyResponse()
      @JvmName("setGenealogyResponse")
      set(value) {
        _builder.setGenealogyResponse(value)
      }
    /**
     * `.VCSEC.GenealogyResponse genealogyResponse = 21;`
     */
    public fun clearGenealogyResponse() {
      _builder.clearGenealogyResponse()
    }
    /**
     * `.VCSEC.GenealogyResponse genealogyResponse = 21;`
     * @return Whether the genealogyResponse field is set.
     */
    public fun hasGenealogyResponse(): kotlin.Boolean {
      return _builder.hasGenealogyResponse()
    }

    /**
     * `.VCSEC.KeyfobInfo keyfobInfo = 23;`
     */
    public var keyfobInfo: com.teslamotors.protocol.VCSEC.KeyfobInfo
      @JvmName("getKeyfobInfo")
      get() = _builder.getKeyfobInfo()
      @JvmName("setKeyfobInfo")
      set(value) {
        _builder.setKeyfobInfo(value)
      }
    /**
     * `.VCSEC.KeyfobInfo keyfobInfo = 23;`
     */
    public fun clearKeyfobInfo() {
      _builder.clearKeyfobInfo()
    }
    /**
     * `.VCSEC.KeyfobInfo keyfobInfo = 23;`
     * @return Whether the keyfobInfo field is set.
     */
    public fun hasKeyfobInfo(): kotlin.Boolean {
      return _builder.hasKeyfobInfo()
    }

    /**
     * `.VCSEC.IMUState_E IMUState = 24;`
     */
    public var iMUState: com.teslamotors.protocol.VCSEC.IMUState_E
      @JvmName("getIMUState")
      get() = _builder.getIMUState()
      @JvmName("setIMUState")
      set(value) {
        _builder.setIMUState(value)
      }
    public var iMUStateValue: kotlin.Int
      @JvmName("getIMUStateValue")
      get() = _builder.getIMUStateValue()
      @JvmName("setIMUStateValue")
      set(value) {
        _builder.setIMUStateValue(value)
      }
    /**
     * `.VCSEC.IMUState_E IMUState = 24;`
     */
    public fun clearIMUState() {
      _builder.clearIMUState()
    }
    /**
     * `.VCSEC.IMUState_E IMUState = 24;`
     * @return Whether the iMUState field is set.
     */
    public fun hasIMUState(): kotlin.Boolean {
      return _builder.hasIMUState()
    }

    /**
     * `.VCSEC.NFCSEState nfcseState = 26;`
     */
    public var nfcseState: com.teslamotors.protocol.VCSEC.NFCSEState
      @JvmName("getNfcseState")
      get() = _builder.getNfcseState()
      @JvmName("setNfcseState")
      set(value) {
        _builder.setNfcseState(value)
      }
    /**
     * `.VCSEC.NFCSEState nfcseState = 26;`
     */
    public fun clearNfcseState() {
      _builder.clearNfcseState()
    }
    /**
     * `.VCSEC.NFCSEState nfcseState = 26;`
     * @return Whether the nfcseState field is set.
     */
    public fun hasNfcseState(): kotlin.Boolean {
      return _builder.hasNfcseState()
    }

    /**
     * `.VCSEC.SleepManagerStats lowPowerDeviceSleepManagerStats = 27;`
     */
    public var lowPowerDeviceSleepManagerStats: com.teslamotors.protocol.VCSEC.SleepManagerStats
      @JvmName("getLowPowerDeviceSleepManagerStats")
      get() = _builder.getLowPowerDeviceSleepManagerStats()
      @JvmName("setLowPowerDeviceSleepManagerStats")
      set(value) {
        _builder.setLowPowerDeviceSleepManagerStats(value)
      }
    /**
     * `.VCSEC.SleepManagerStats lowPowerDeviceSleepManagerStats = 27;`
     */
    public fun clearLowPowerDeviceSleepManagerStats() {
      _builder.clearLowPowerDeviceSleepManagerStats()
    }
    /**
     * `.VCSEC.SleepManagerStats lowPowerDeviceSleepManagerStats = 27;`
     * @return Whether the lowPowerDeviceSleepManagerStats field is set.
     */
    public fun hasLowPowerDeviceSleepManagerStats(): kotlin.Boolean {
      return _builder.hasLowPowerDeviceSleepManagerStats()
    }
    public val subMessageCase: com.teslamotors.protocol.VCSEC.UnsignedMessageShort.SubMessageCase
      @JvmName("getSubMessageCase")
      get() = _builder.getSubMessageCase()

    public fun clearSubMessage() {
      _builder.clearSubMessage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.teslamotors.protocol.VCSEC.UnsignedMessageShort.copy(block: com.teslamotors.protocol.UnsignedMessageShortKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.UnsignedMessageShort =
  com.teslamotors.protocol.UnsignedMessageShortKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.teslamotors.protocol.VCSEC.UnsignedMessageShortOrBuilder.authenticationResponseOrNull: com.teslamotors.protocol.VCSEC.AuthenticationResponse?
  get() = if (hasAuthenticationResponse()) getAuthenticationResponse() else null

public val com.teslamotors.protocol.VCSEC.UnsignedMessageShortOrBuilder.updaterResponseOrNull: com.teslamotors.protocol.VCSEC.UpdaterResponse?
  get() = if (hasUpdaterResponse()) getUpdaterResponse() else null

public val com.teslamotors.protocol.VCSEC.UnsignedMessageShortOrBuilder.genealogyResponseOrNull: com.teslamotors.protocol.VCSEC.GenealogyResponse?
  get() = if (hasGenealogyResponse()) getGenealogyResponse() else null

public val com.teslamotors.protocol.VCSEC.UnsignedMessageShortOrBuilder.keyfobInfoOrNull: com.teslamotors.protocol.VCSEC.KeyfobInfo?
  get() = if (hasKeyfobInfo()) getKeyfobInfo() else null

public val com.teslamotors.protocol.VCSEC.UnsignedMessageShortOrBuilder.nfcseStateOrNull: com.teslamotors.protocol.VCSEC.NFCSEState?
  get() = if (hasNfcseState()) getNfcseState() else null

public val com.teslamotors.protocol.VCSEC.UnsignedMessageShortOrBuilder.lowPowerDeviceSleepManagerStatsOrNull: com.teslamotors.protocol.VCSEC.SleepManagerStats?
  get() = if (hasLowPowerDeviceSleepManagerStats()) getLowPowerDeviceSleepManagerStats() else null

