// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/VCSECv3.10.14.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.teslamotors.protocol;

@kotlin.jvm.JvmName("-initializeupdaterStatus")
public inline fun updaterStatus(block: com.teslamotors.protocol.UpdaterStatusKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.UpdaterStatus =
  com.teslamotors.protocol.UpdaterStatusKt.Dsl._create(com.teslamotors.protocol.VCSEC.UpdaterStatus.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `VCSEC.UpdaterStatus`
 */
public object UpdaterStatusKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.teslamotors.protocol.VCSEC.UpdaterStatus.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.teslamotors.protocol.VCSEC.UpdaterStatus.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.teslamotors.protocol.VCSEC.UpdaterStatus = _builder.build()

    /**
     * `.VCSEC.UpdaterStatusCode statusCode = 1;`
     */
    public var statusCode: com.teslamotors.protocol.VCSEC.UpdaterStatusCode
      @JvmName("getStatusCode")
      get() = _builder.getStatusCode()
      @JvmName("setStatusCode")
      set(value) {
        _builder.setStatusCode(value)
      }
    public var statusCodeValue: kotlin.Int
      @JvmName("getStatusCodeValue")
      get() = _builder.getStatusCodeValue()
      @JvmName("setStatusCodeValue")
      set(value) {
        _builder.setStatusCodeValue(value)
      }
    /**
     * `.VCSEC.UpdaterStatusCode statusCode = 1;`
     */
    public fun clearStatusCode() {
      _builder.clearStatusCode()
    }

    /**
     * `.VCSEC.UpdaterLocation location = 2;`
     */
    public var location: com.teslamotors.protocol.VCSEC.UpdaterLocation
      @JvmName("getLocation")
      get() = _builder.getLocation()
      @JvmName("setLocation")
      set(value) {
        _builder.setLocation(value)
      }
    public var locationValue: kotlin.Int
      @JvmName("getLocationValue")
      get() = _builder.getLocationValue()
      @JvmName("setLocationValue")
      set(value) {
        _builder.setLocationValue(value)
      }
    /**
     * `.VCSEC.UpdaterLocation location = 2;`
     */
    public fun clearLocation() {
      _builder.clearLocation()
    }

    /**
     * `uint32 nextAddressNumber = 3;`
     */
    public var nextAddressNumber: kotlin.Int
      @JvmName("getNextAddressNumber")
      get() = _builder.getNextAddressNumber()
      @JvmName("setNextAddressNumber")
      set(value) {
        _builder.setNextAddressNumber(value)
      }
    /**
     * `uint32 nextAddressNumber = 3;`
     */
    public fun clearNextAddressNumber() {
      _builder.clearNextAddressNumber()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.teslamotors.protocol.VCSEC.UpdaterStatus.copy(block: com.teslamotors.protocol.UpdaterStatusKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.UpdaterStatus =
  com.teslamotors.protocol.UpdaterStatusKt.Dsl._create(this.toBuilder()).apply { block() }._build()

