// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/VCSECv3.10.14.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.teslamotors.protocol;

@kotlin.jvm.JvmName("-initializevehicleStatus")
public inline fun vehicleStatus(block: com.teslamotors.protocol.VehicleStatusKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.VehicleStatus =
  com.teslamotors.protocol.VehicleStatusKt.Dsl._create(com.teslamotors.protocol.VCSEC.VehicleStatus.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `VCSEC.VehicleStatus`
 */
public object VehicleStatusKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.teslamotors.protocol.VCSEC.VehicleStatus.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.teslamotors.protocol.VCSEC.VehicleStatus.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.teslamotors.protocol.VCSEC.VehicleStatus = _builder.build()

    /**
     * `.VCSEC.ClosureStatuses closureStatuses = 1;`
     */
    public var closureStatuses: com.teslamotors.protocol.VCSEC.ClosureStatuses
      @JvmName("getClosureStatuses")
      get() = _builder.getClosureStatuses()
      @JvmName("setClosureStatuses")
      set(value) {
        _builder.setClosureStatuses(value)
      }
    /**
     * `.VCSEC.ClosureStatuses closureStatuses = 1;`
     */
    public fun clearClosureStatuses() {
      _builder.clearClosureStatuses()
    }
    /**
     * `.VCSEC.ClosureStatuses closureStatuses = 1;`
     * @return Whether the closureStatuses field is set.
     */
    public fun hasClosureStatuses(): kotlin.Boolean {
      return _builder.hasClosureStatuses()
    }

    /**
     * `.VCSEC.VehicleLockState_E vehicleLockState = 2;`
     */
    public var vehicleLockState: com.teslamotors.protocol.VCSEC.VehicleLockState_E
      @JvmName("getVehicleLockState")
      get() = _builder.getVehicleLockState()
      @JvmName("setVehicleLockState")
      set(value) {
        _builder.setVehicleLockState(value)
      }
    public var vehicleLockStateValue: kotlin.Int
      @JvmName("getVehicleLockStateValue")
      get() = _builder.getVehicleLockStateValue()
      @JvmName("setVehicleLockStateValue")
      set(value) {
        _builder.setVehicleLockStateValue(value)
      }
    /**
     * `.VCSEC.VehicleLockState_E vehicleLockState = 2;`
     */
    public fun clearVehicleLockState() {
      _builder.clearVehicleLockState()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.teslamotors.protocol.VCSEC.VehicleStatus.copy(block: com.teslamotors.protocol.VehicleStatusKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.VehicleStatus =
  com.teslamotors.protocol.VehicleStatusKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.teslamotors.protocol.VCSEC.VehicleStatusOrBuilder.closureStatusesOrNull: com.teslamotors.protocol.VCSEC.ClosureStatuses?
  get() = if (hasClosureStatuses()) getClosureStatuses() else null

