// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/VCSECv3.10.14.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.teslamotors.protocol;

@kotlin.jvm.JvmName("-initializevehicleInfo")
public inline fun vehicleInfo(block: com.teslamotors.protocol.VehicleInfoKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.VehicleInfo =
  com.teslamotors.protocol.VehicleInfoKt.Dsl._create(com.teslamotors.protocol.VCSEC.VehicleInfo.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `VCSEC.VehicleInfo`
 */
public object VehicleInfoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.teslamotors.protocol.VCSEC.VehicleInfo.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.teslamotors.protocol.VCSEC.VehicleInfo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.teslamotors.protocol.VCSEC.VehicleInfo = _builder.build()

    /**
     * `string VIN = 1;`
     */
    public var vIN: kotlin.String
      @JvmName("getVIN")
      get() = _builder.getVIN()
      @JvmName("setVIN")
      set(value) {
        _builder.setVIN(value)
      }
    /**
     * `string VIN = 1;`
     */
    public fun clearVIN() {
      _builder.clearVIN()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.teslamotors.protocol.VCSEC.VehicleInfo.copy(block: com.teslamotors.protocol.VehicleInfoKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.VehicleInfo =
  com.teslamotors.protocol.VehicleInfoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

