// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/VCSECv3.10.14.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.teslamotors.protocol;

@kotlin.jvm.JvmName("-initializeverifyAndInstallApp")
public inline fun verifyAndInstallApp(block: com.teslamotors.protocol.VerifyAndInstallAppKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.VerifyAndInstallApp =
  com.teslamotors.protocol.VerifyAndInstallAppKt.Dsl._create(com.teslamotors.protocol.VCSEC.VerifyAndInstallApp.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `VCSEC.VerifyAndInstallApp`
 */
public object VerifyAndInstallAppKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.teslamotors.protocol.VCSEC.VerifyAndInstallApp.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.teslamotors.protocol.VCSEC.VerifyAndInstallApp.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.teslamotors.protocol.VCSEC.VerifyAndInstallApp = _builder.build()

    /**
     * `bytes sha256 = 1;`
     */
    public var sha256: com.google.protobuf.ByteString
      @JvmName("getSha256")
      get() = _builder.getSha256()
      @JvmName("setSha256")
      set(value) {
        _builder.setSha256(value)
      }
    /**
     * `bytes sha256 = 1;`
     */
    public fun clearSha256() {
      _builder.clearSha256()
    }

    /**
     * `bytes rValue = 2;`
     */
    public var rValue: com.google.protobuf.ByteString
      @JvmName("getRValue")
      get() = _builder.getRValue()
      @JvmName("setRValue")
      set(value) {
        _builder.setRValue(value)
      }
    /**
     * `bytes rValue = 2;`
     */
    public fun clearRValue() {
      _builder.clearRValue()
    }

    /**
     * `bytes sValue = 3;`
     */
    public var sValue: com.google.protobuf.ByteString
      @JvmName("getSValue")
      get() = _builder.getSValue()
      @JvmName("setSValue")
      set(value) {
        _builder.setSValue(value)
      }
    /**
     * `bytes sValue = 3;`
     */
    public fun clearSValue() {
      _builder.clearSValue()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.teslamotors.protocol.VCSEC.VerifyAndInstallApp.copy(block: com.teslamotors.protocol.VerifyAndInstallAppKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.VerifyAndInstallApp =
  com.teslamotors.protocol.VerifyAndInstallAppKt.Dsl._create(this.toBuilder()).apply { block() }._build()

