// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/VCSECv3.10.14.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.teslamotors.protocol;

@kotlin.jvm.JvmName("-initializewhitelistInfo")
public inline fun whitelistInfo(block: com.teslamotors.protocol.WhitelistInfoKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.WhitelistInfo =
  com.teslamotors.protocol.WhitelistInfoKt.Dsl._create(com.teslamotors.protocol.VCSEC.WhitelistInfo.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `VCSEC.WhitelistInfo`
 */
public object WhitelistInfoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.teslamotors.protocol.VCSEC.WhitelistInfo.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.teslamotors.protocol.VCSEC.WhitelistInfo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.teslamotors.protocol.VCSEC.WhitelistInfo = _builder.build()

    /**
     * `uint32 numberOfEntries = 1;`
     */
    public var numberOfEntries: kotlin.Int
      @JvmName("getNumberOfEntries")
      get() = _builder.getNumberOfEntries()
      @JvmName("setNumberOfEntries")
      set(value) {
        _builder.setNumberOfEntries(value)
      }
    /**
     * `uint32 numberOfEntries = 1;`
     */
    public fun clearNumberOfEntries() {
      _builder.clearNumberOfEntries()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class WhitelistEntriesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .VCSEC.KeyIdentifier whitelistEntries = 2;`
     */
     public val whitelistEntries: com.google.protobuf.kotlin.DslList<com.teslamotors.protocol.VCSEC.KeyIdentifier, WhitelistEntriesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getWhitelistEntriesList()
      )
    /**
     * `repeated .VCSEC.KeyIdentifier whitelistEntries = 2;`
     * @param value The whitelistEntries to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addWhitelistEntries")
    public fun com.google.protobuf.kotlin.DslList<com.teslamotors.protocol.VCSEC.KeyIdentifier, WhitelistEntriesProxy>.add(value: com.teslamotors.protocol.VCSEC.KeyIdentifier) {
      _builder.addWhitelistEntries(value)
    }
    /**
     * `repeated .VCSEC.KeyIdentifier whitelistEntries = 2;`
     * @param value The whitelistEntries to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignWhitelistEntries")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.teslamotors.protocol.VCSEC.KeyIdentifier, WhitelistEntriesProxy>.plusAssign(value: com.teslamotors.protocol.VCSEC.KeyIdentifier) {
      add(value)
    }
    /**
     * `repeated .VCSEC.KeyIdentifier whitelistEntries = 2;`
     * @param values The whitelistEntries to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllWhitelistEntries")
    public fun com.google.protobuf.kotlin.DslList<com.teslamotors.protocol.VCSEC.KeyIdentifier, WhitelistEntriesProxy>.addAll(values: kotlin.collections.Iterable<com.teslamotors.protocol.VCSEC.KeyIdentifier>) {
      _builder.addAllWhitelistEntries(values)
    }
    /**
     * `repeated .VCSEC.KeyIdentifier whitelistEntries = 2;`
     * @param values The whitelistEntries to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllWhitelistEntries")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.teslamotors.protocol.VCSEC.KeyIdentifier, WhitelistEntriesProxy>.plusAssign(values: kotlin.collections.Iterable<com.teslamotors.protocol.VCSEC.KeyIdentifier>) {
      addAll(values)
    }
    /**
     * `repeated .VCSEC.KeyIdentifier whitelistEntries = 2;`
     * @param index The index to set the value at.
     * @param value The whitelistEntries to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setWhitelistEntries")
    public operator fun com.google.protobuf.kotlin.DslList<com.teslamotors.protocol.VCSEC.KeyIdentifier, WhitelistEntriesProxy>.set(index: kotlin.Int, value: com.teslamotors.protocol.VCSEC.KeyIdentifier) {
      _builder.setWhitelistEntries(index, value)
    }
    /**
     * `repeated .VCSEC.KeyIdentifier whitelistEntries = 2;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearWhitelistEntries")
    public fun com.google.protobuf.kotlin.DslList<com.teslamotors.protocol.VCSEC.KeyIdentifier, WhitelistEntriesProxy>.clear() {
      _builder.clearWhitelistEntries()
    }

  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.teslamotors.protocol.VCSEC.WhitelistInfo.copy(block: com.teslamotors.protocol.WhitelistInfoKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.WhitelistInfo =
  com.teslamotors.protocol.WhitelistInfoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

