// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/VCSECv3.10.14.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.teslamotors.protocol;

@kotlin.jvm.JvmName("-initializewhitelistOperationStatus")
public inline fun whitelistOperationStatus(block: com.teslamotors.protocol.WhitelistOperation_statusKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.WhitelistOperation_status =
  com.teslamotors.protocol.WhitelistOperation_statusKt.Dsl._create(com.teslamotors.protocol.VCSEC.WhitelistOperation_status.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `VCSEC.WhitelistOperation_status`
 */
public object WhitelistOperation_statusKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.teslamotors.protocol.VCSEC.WhitelistOperation_status.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.teslamotors.protocol.VCSEC.WhitelistOperation_status.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.teslamotors.protocol.VCSEC.WhitelistOperation_status = _builder.build()

    /**
     * `.VCSEC.WhitelistOperation_information_E whitelistOperationInformation = 1;`
     */
    public var whitelistOperationInformation: com.teslamotors.protocol.VCSEC.WhitelistOperation_information_E
      @JvmName("getWhitelistOperationInformation")
      get() = _builder.getWhitelistOperationInformation()
      @JvmName("setWhitelistOperationInformation")
      set(value) {
        _builder.setWhitelistOperationInformation(value)
      }
    public var whitelistOperationInformationValue: kotlin.Int
      @JvmName("getWhitelistOperationInformationValue")
      get() = _builder.getWhitelistOperationInformationValue()
      @JvmName("setWhitelistOperationInformationValue")
      set(value) {
        _builder.setWhitelistOperationInformationValue(value)
      }
    /**
     * `.VCSEC.WhitelistOperation_information_E whitelistOperationInformation = 1;`
     */
    public fun clearWhitelistOperationInformation() {
      _builder.clearWhitelistOperationInformation()
    }

    /**
     * `.VCSEC.KeyIdentifier signerOfOperation = 2;`
     */
    public var signerOfOperation: com.teslamotors.protocol.VCSEC.KeyIdentifier
      @JvmName("getSignerOfOperation")
      get() = _builder.getSignerOfOperation()
      @JvmName("setSignerOfOperation")
      set(value) {
        _builder.setSignerOfOperation(value)
      }
    /**
     * `.VCSEC.KeyIdentifier signerOfOperation = 2;`
     */
    public fun clearSignerOfOperation() {
      _builder.clearSignerOfOperation()
    }
    /**
     * `.VCSEC.KeyIdentifier signerOfOperation = 2;`
     * @return Whether the signerOfOperation field is set.
     */
    public fun hasSignerOfOperation(): kotlin.Boolean {
      return _builder.hasSignerOfOperation()
    }

    /**
     * `.VCSEC.OperationStatus_E operationStatus = 3;`
     */
    public var operationStatus: com.teslamotors.protocol.VCSEC.OperationStatus_E
      @JvmName("getOperationStatus")
      get() = _builder.getOperationStatus()
      @JvmName("setOperationStatus")
      set(value) {
        _builder.setOperationStatus(value)
      }
    public var operationStatusValue: kotlin.Int
      @JvmName("getOperationStatusValue")
      get() = _builder.getOperationStatusValue()
      @JvmName("setOperationStatusValue")
      set(value) {
        _builder.setOperationStatusValue(value)
      }
    /**
     * `.VCSEC.OperationStatus_E operationStatus = 3;`
     */
    public fun clearOperationStatus() {
      _builder.clearOperationStatus()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.teslamotors.protocol.VCSEC.WhitelistOperation_status.copy(block: com.teslamotors.protocol.WhitelistOperation_statusKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.WhitelistOperation_status =
  com.teslamotors.protocol.WhitelistOperation_statusKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.teslamotors.protocol.VCSEC.WhitelistOperation_statusOrBuilder.signerOfOperationOrNull: com.teslamotors.protocol.VCSEC.KeyIdentifier?
  get() = if (hasSignerOfOperation()) getSignerOfOperation() else null

