// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/VCSECv3.10.14.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.teslamotors.protocol;

@kotlin.jvm.JvmName("-initializewhitelistOperation")
public inline fun whitelistOperation(block: com.teslamotors.protocol.WhitelistOperationKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.WhitelistOperation =
  com.teslamotors.protocol.WhitelistOperationKt.Dsl._create(com.teslamotors.protocol.VCSEC.WhitelistOperation.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `VCSEC.WhitelistOperation`
 */
public object WhitelistOperationKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.teslamotors.protocol.VCSEC.WhitelistOperation.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.teslamotors.protocol.VCSEC.WhitelistOperation.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.teslamotors.protocol.VCSEC.WhitelistOperation = _builder.build()

    /**
     * `.VCSEC.KeyMetadata metadataForKey = 6;`
     */
    public var metadataForKey: com.teslamotors.protocol.VCSEC.KeyMetadata
      @JvmName("getMetadataForKey")
      get() = _builder.getMetadataForKey()
      @JvmName("setMetadataForKey")
      set(value) {
        _builder.setMetadataForKey(value)
      }
    /**
     * `.VCSEC.KeyMetadata metadataForKey = 6;`
     */
    public fun clearMetadataForKey() {
      _builder.clearMetadataForKey()
    }
    /**
     * `.VCSEC.KeyMetadata metadataForKey = 6;`
     * @return Whether the metadataForKey field is set.
     */
    public fun hasMetadataForKey(): kotlin.Boolean {
      return _builder.hasMetadataForKey()
    }

    /**
     * `.VCSEC.PublicKey addPublicKeyToWhitelist = 1;`
     */
    public var addPublicKeyToWhitelist: com.teslamotors.protocol.VCSEC.PublicKey
      @JvmName("getAddPublicKeyToWhitelist")
      get() = _builder.getAddPublicKeyToWhitelist()
      @JvmName("setAddPublicKeyToWhitelist")
      set(value) {
        _builder.setAddPublicKeyToWhitelist(value)
      }
    /**
     * `.VCSEC.PublicKey addPublicKeyToWhitelist = 1;`
     */
    public fun clearAddPublicKeyToWhitelist() {
      _builder.clearAddPublicKeyToWhitelist()
    }
    /**
     * `.VCSEC.PublicKey addPublicKeyToWhitelist = 1;`
     * @return Whether the addPublicKeyToWhitelist field is set.
     */
    public fun hasAddPublicKeyToWhitelist(): kotlin.Boolean {
      return _builder.hasAddPublicKeyToWhitelist()
    }

    /**
     * `.VCSEC.PublicKey removePublicKeyFromWhitelist = 2;`
     */
    public var removePublicKeyFromWhitelist: com.teslamotors.protocol.VCSEC.PublicKey
      @JvmName("getRemovePublicKeyFromWhitelist")
      get() = _builder.getRemovePublicKeyFromWhitelist()
      @JvmName("setRemovePublicKeyFromWhitelist")
      set(value) {
        _builder.setRemovePublicKeyFromWhitelist(value)
      }
    /**
     * `.VCSEC.PublicKey removePublicKeyFromWhitelist = 2;`
     */
    public fun clearRemovePublicKeyFromWhitelist() {
      _builder.clearRemovePublicKeyFromWhitelist()
    }
    /**
     * `.VCSEC.PublicKey removePublicKeyFromWhitelist = 2;`
     * @return Whether the removePublicKeyFromWhitelist field is set.
     */
    public fun hasRemovePublicKeyFromWhitelist(): kotlin.Boolean {
      return _builder.hasRemovePublicKeyFromWhitelist()
    }

    /**
     * `.VCSEC.PermissionChange addPermissionsToPublicKey = 3;`
     */
    public var addPermissionsToPublicKey: com.teslamotors.protocol.VCSEC.PermissionChange
      @JvmName("getAddPermissionsToPublicKey")
      get() = _builder.getAddPermissionsToPublicKey()
      @JvmName("setAddPermissionsToPublicKey")
      set(value) {
        _builder.setAddPermissionsToPublicKey(value)
      }
    /**
     * `.VCSEC.PermissionChange addPermissionsToPublicKey = 3;`
     */
    public fun clearAddPermissionsToPublicKey() {
      _builder.clearAddPermissionsToPublicKey()
    }
    /**
     * `.VCSEC.PermissionChange addPermissionsToPublicKey = 3;`
     * @return Whether the addPermissionsToPublicKey field is set.
     */
    public fun hasAddPermissionsToPublicKey(): kotlin.Boolean {
      return _builder.hasAddPermissionsToPublicKey()
    }

    /**
     * `.VCSEC.PermissionChange removePermissionsFromPublicKey = 4;`
     */
    public var removePermissionsFromPublicKey: com.teslamotors.protocol.VCSEC.PermissionChange
      @JvmName("getRemovePermissionsFromPublicKey")
      get() = _builder.getRemovePermissionsFromPublicKey()
      @JvmName("setRemovePermissionsFromPublicKey")
      set(value) {
        _builder.setRemovePermissionsFromPublicKey(value)
      }
    /**
     * `.VCSEC.PermissionChange removePermissionsFromPublicKey = 4;`
     */
    public fun clearRemovePermissionsFromPublicKey() {
      _builder.clearRemovePermissionsFromPublicKey()
    }
    /**
     * `.VCSEC.PermissionChange removePermissionsFromPublicKey = 4;`
     * @return Whether the removePermissionsFromPublicKey field is set.
     */
    public fun hasRemovePermissionsFromPublicKey(): kotlin.Boolean {
      return _builder.hasRemovePermissionsFromPublicKey()
    }

    /**
     * `.VCSEC.PermissionChange addKeyToWhitelistAndAddPermissions = 5;`
     */
    public var addKeyToWhitelistAndAddPermissions: com.teslamotors.protocol.VCSEC.PermissionChange
      @JvmName("getAddKeyToWhitelistAndAddPermissions")
      get() = _builder.getAddKeyToWhitelistAndAddPermissions()
      @JvmName("setAddKeyToWhitelistAndAddPermissions")
      set(value) {
        _builder.setAddKeyToWhitelistAndAddPermissions(value)
      }
    /**
     * `.VCSEC.PermissionChange addKeyToWhitelistAndAddPermissions = 5;`
     */
    public fun clearAddKeyToWhitelistAndAddPermissions() {
      _builder.clearAddKeyToWhitelistAndAddPermissions()
    }
    /**
     * `.VCSEC.PermissionChange addKeyToWhitelistAndAddPermissions = 5;`
     * @return Whether the addKeyToWhitelistAndAddPermissions field is set.
     */
    public fun hasAddKeyToWhitelistAndAddPermissions(): kotlin.Boolean {
      return _builder.hasAddKeyToWhitelistAndAddPermissions()
    }

    /**
     * `.VCSEC.PermissionChange updateKeyAndPermissions = 7;`
     */
    public var updateKeyAndPermissions: com.teslamotors.protocol.VCSEC.PermissionChange
      @JvmName("getUpdateKeyAndPermissions")
      get() = _builder.getUpdateKeyAndPermissions()
      @JvmName("setUpdateKeyAndPermissions")
      set(value) {
        _builder.setUpdateKeyAndPermissions(value)
      }
    /**
     * `.VCSEC.PermissionChange updateKeyAndPermissions = 7;`
     */
    public fun clearUpdateKeyAndPermissions() {
      _builder.clearUpdateKeyAndPermissions()
    }
    /**
     * `.VCSEC.PermissionChange updateKeyAndPermissions = 7;`
     * @return Whether the updateKeyAndPermissions field is set.
     */
    public fun hasUpdateKeyAndPermissions(): kotlin.Boolean {
      return _builder.hasUpdateKeyAndPermissions()
    }
    public val subMessageCase: com.teslamotors.protocol.VCSEC.WhitelistOperation.SubMessageCase
      @JvmName("getSubMessageCase")
      get() = _builder.getSubMessageCase()

    public fun clearSubMessage() {
      _builder.clearSubMessage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.teslamotors.protocol.VCSEC.WhitelistOperation.copy(block: com.teslamotors.protocol.WhitelistOperationKt.Dsl.() -> kotlin.Unit): com.teslamotors.protocol.VCSEC.WhitelistOperation =
  com.teslamotors.protocol.WhitelistOperationKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.teslamotors.protocol.VCSEC.WhitelistOperationOrBuilder.metadataForKeyOrNull: com.teslamotors.protocol.VCSEC.KeyMetadata?
  get() = if (hasMetadataForKey()) getMetadataForKey() else null

public val com.teslamotors.protocol.VCSEC.WhitelistOperationOrBuilder.addPublicKeyToWhitelistOrNull: com.teslamotors.protocol.VCSEC.PublicKey?
  get() = if (hasAddPublicKeyToWhitelist()) getAddPublicKeyToWhitelist() else null

public val com.teslamotors.protocol.VCSEC.WhitelistOperationOrBuilder.removePublicKeyFromWhitelistOrNull: com.teslamotors.protocol.VCSEC.PublicKey?
  get() = if (hasRemovePublicKeyFromWhitelist()) getRemovePublicKeyFromWhitelist() else null

public val com.teslamotors.protocol.VCSEC.WhitelistOperationOrBuilder.addPermissionsToPublicKeyOrNull: com.teslamotors.protocol.VCSEC.PermissionChange?
  get() = if (hasAddPermissionsToPublicKey()) getAddPermissionsToPublicKey() else null

public val com.teslamotors.protocol.VCSEC.WhitelistOperationOrBuilder.removePermissionsFromPublicKeyOrNull: com.teslamotors.protocol.VCSEC.PermissionChange?
  get() = if (hasRemovePermissionsFromPublicKey()) getRemovePermissionsFromPublicKey() else null

public val com.teslamotors.protocol.VCSEC.WhitelistOperationOrBuilder.addKeyToWhitelistAndAddPermissionsOrNull: com.teslamotors.protocol.VCSEC.PermissionChange?
  get() = if (hasAddKeyToWhitelistAndAddPermissions()) getAddKeyToWhitelistAndAddPermissions() else null

public val com.teslamotors.protocol.VCSEC.WhitelistOperationOrBuilder.updateKeyAndPermissionsOrNull: com.teslamotors.protocol.VCSEC.PermissionChange?
  get() = if (hasUpdateKeyAndPermissions()) getUpdateKeyAndPermissions() else null

